// Physical AI関連イベントの正本データ。表示は physical_ai_events_overview.html が担当する。
window.PHYSICAL_AI_EVENTS = [
  {
    "id": "20260106-ces-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-01-06",
    "year": 2026,
    "dateLabel": "1月6–9日",
    "name": "CES 2026",
    "budgetCandidate": true,
    "importance": "★★☆☆☆",
    "businessFit": "★★☆☆☆",
    "category": "Technology Foresight / Innovation",
    "type": "技術カンファレンス・サミット",
    "location": "Las Vegas, Nevada, United States",
    "status": "参加済み",
    "assignment": "長澤・西田・傳田",
    "purpose": "技術探索・事業探索・スタートアップ探索枠"
  },
  {
    "id": "20260120-aaai-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-01-20",
    "year": 2026,
    "dateLabel": "1月20–27日",
    "name": "AAAI 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★☆☆☆☆",
    "category": "Robot Learning / AI基盤",
    "type": "学会・専門会議",
    "location": "Singapore EXPO, Singapore",
    "status": "不参加",
    "assignment": "—",
    "purpose": "AI全般の総合会議。推論、探索、計画、知識表現、機械学習応用などは含むが、ロボット実機、身体性AI、Sim2Real、ロボット学習が会議全体の主題ではない。AI×Robotics調査ではCoRL / ICRA / CVPR / GTCを優先するため、2026年は不参加。"
  },
  {
    "id": "20260211-semicon-korea-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-02-11",
    "year": 2026,
    "dateLabel": "2月11–13日",
    "name": "SEMICON Korea 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★★☆☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "COEX, Seoul, Republic of Korea",
    "status": "不参加",
    "assignment": "—",
    "purpose": "半導体製造装置・材料・プロセス・先端パッケージング。基準日以前に開催済みのため不参加。"
  },
  {
    "id": "20260309-amc-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-03-09",
    "year": 2026,
    "dateLabel": "3月9–11日",
    "name": "AMC 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★☆",
    "category": "Control / Motion / Systems",
    "type": "学会・専門会議",
    "location": "Daegu, Republic of Korea",
    "status": "参加済み",
    "assignment": "橋本・田端",
    "purpose": "Advanced Motion Control。制御・モーション基盤の補完実績。小規模専門会議として1名程度の参加で十分。"
  },
  {
    "id": "20260310-jec-world-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-03-10",
    "year": 2026,
    "dateLabel": "3月10–12日",
    "name": "JEC World 2026",
    "budgetCandidate": true,
    "importance": "★★☆☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Paris-Nord Villepinte, France",
    "status": "参加済み",
    "assignment": "仲西・谷川・渡辺",
    "purpose": "複合材料、軽量化、材料加工・産業応用"
  },
  {
    "id": "20260310-embedded-world-germany-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-03-10",
    "year": 2026,
    "dateLabel": "3月10–12日",
    "name": "embedded world Germany 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★☆",
    "category": "Embedded / Edge / Real-time Systems",
    "type": "展示会・見本市",
    "location": "Nuremberg, Germany",
    "status": "不参加",
    "assignment": "—",
    "purpose": "組込み、エッジAI、リアルタイム、機能安全、産業用コンピューティングの実装基盤として重要。ただし2026年は不参加。"
  },
  {
    "id": "20260312-sxsw-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-03-12",
    "year": 2026,
    "dateLabel": "3月12–18日",
    "name": "SXSW 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★☆☆☆☆",
    "category": "Technology Foresight / Innovation",
    "type": "技術カンファレンス・サミット",
    "location": "Austin, Texas, United States",
    "status": "参加済み",
    "assignment": "尾中",
    "purpose": "技術探索・事業探索・社会実装トレンド"
  },
  {
    "id": "20260316-gtc-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-03-16",
    "year": 2026,
    "dateLabel": "3月16–19日",
    "name": "GTC 2026",
    "budgetCandidate": true,
    "importance": "★★★★★",
    "businessFit": "★★★★☆",
    "category": "Technology Foresight / Innovation",
    "type": "技術カンファレンス・サミット",
    "location": "San Jose McEnery Convention Center, San Jose, CA, United States",
    "status": "不参加",
    "assignment": "—",
    "purpose": "NVIDIA GTC。Physical AI、AI基盤、GPU、ロボティクス基盤、シミュレーション、Omniverse、Edge AIの観点で極めて重要。ただし2026年は不参加。"
  },
  {
    "id": "20260316-hri-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-03-16",
    "year": 2026,
    "dateLabel": "3月16–19日",
    "name": "HRI 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★☆☆☆",
    "category": "HRI / Human Factors",
    "type": "学会・専門会議",
    "location": "Edinburgh, United Kingdom",
    "status": "不参加",
    "assignment": "—",
    "purpose": "人協働・受容性・Human-Robot Interaction。後追い対象"
  },
  {
    "id": "20260320-3dv-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-03-20",
    "year": 2026,
    "dateLabel": "3月20–23日",
    "name": "3DV 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★☆☆",
    "category": "Vision / 3D認識",
    "type": "学会・専門会議",
    "location": "Vancouver Convention Centre, Vancouver, BC, Canada",
    "status": "不参加",
    "assignment": "—",
    "purpose": "3D Vision。3D認識・空間理解の補完候補だが、基準日以前に開催済みのため不参加。"
  },
  {
    "id": "20260324-logimat-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-03-24",
    "year": 2026,
    "dateLabel": "3月24–26日",
    "name": "LogiMAT 2026",
    "budgetCandidate": true,
    "importance": "★★★☆☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Messe Stuttgart, Stuttgart, Germany",
    "status": "参加済み",
    "assignment": "榎・鉢木",
    "purpose": "欧州物流・倉庫自動化"
  },
  {
    "id": "20260325-semicon-china-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-03-25",
    "year": 2026,
    "dateLabel": "3月25–27日",
    "name": "SEMICON China 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★★☆☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Shanghai New International Expo Centre, Shanghai, China",
    "status": "不参加",
    "assignment": "—",
    "purpose": "中国半導体製造装置・材料・プロセス。基準日以前に開催済みのため不参加。"
  },
  {
    "id": "20260407-robosoft-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-04-07",
    "year": 2026,
    "dateLabel": "4月7–11日",
    "name": "RoboSoft 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★☆☆",
    "category": "Soft Robotics / Haptics",
    "type": "学会・専門会議",
    "location": "金沢, Japan",
    "status": "参加済み",
    "assignment": "中島・高野",
    "purpose": "ソフトロボティクス、触覚、柔軟機構、接触作業。Soft Roboticsカテゴリの代表実績だが、AI×Robotics全体では補完領域。"
  },
  {
    "id": "20260413-modex-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-04-13",
    "year": 2026,
    "dateLabel": "4月13–16日",
    "name": "MODEX 2026",
    "budgetCandidate": true,
    "importance": "★★★☆☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Georgia World Congress Center, Atlanta, GA, United States",
    "status": "参加済み",
    "assignment": "北尾・山根",
    "purpose": "北米物流・マテハン・倉庫自動化"
  },
  {
    "id": "20260414-interclean-amsterdam-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-04-14",
    "year": 2026,
    "dateLabel": "4月14–17日",
    "name": "Interclean Amsterdam 2026",
    "budgetCandidate": true,
    "importance": "★★☆☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "RAI Amsterdam, Amsterdam, Netherlands",
    "status": "参加済み",
    "assignment": "仲西・下本・酒井・田原",
    "purpose": "業務用清掃、施設管理、清掃ロボット、衛生・メンテナンス"
  },
  {
    "id": "20260420-hannover-messe-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-04-20",
    "year": 2026,
    "dateLabel": "4月20–24日",
    "name": "Hannover Messe 2026",
    "budgetCandidate": true,
    "importance": "★★★☆☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Hannover Exhibition Grounds, Hannover, Germany",
    "status": "参加済み",
    "assignment": "谷阪・保木・田中大・田原・仲西",
    "purpose": "総合産業・FA・スマート製造"
  },
  {
    "id": "20260423-iclr-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-04-23",
    "year": 2026,
    "dateLabel": "4月23–27日",
    "name": "ICLR 2026",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★☆☆☆",
    "category": "Robot Learning / AI基盤",
    "type": "学会・専門会議",
    "location": "Riocentro Convention and Event Center, Rio de Janeiro, Brazil",
    "status": "論文・発表追跡",
    "assignment": "—",
    "purpose": "AI基盤・表現学習。現地参加せず、Robot Learning / Embodied AI関連の論文・Workshopを追跡"
  },
  {
    "id": "20260504-act-expo-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-05-04",
    "year": 2026,
    "dateLabel": "5月4–7日",
    "name": "ACT Expo 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★★☆☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Las Vegas Convention Center, Las Vegas, NV, United States",
    "status": "参加済み",
    "assignment": "仲西・谷川",
    "purpose": "EV、水素、Clean Fleet、充電・燃料インフラ、AI・自律システム"
  },
  {
    "id": "20260505-semicon-southeast-asia-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-05-05",
    "year": 2026,
    "dateLabel": "5月5–7日",
    "name": "SEMICON Southeast Asia 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "MITEC, Kuala Lumpur, Malaysia",
    "status": "参加済み",
    "assignment": "村上・大槻",
    "purpose": "東南アジアの半導体製造装置・材料・プロセス。参加内容を社内共有対象とする。"
  },
  {
    "id": "20260517-acsmo-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-05-17",
    "year": 2026,
    "dateLabel": "5月17–21日",
    "name": "ACSMO 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★☆",
    "category": "Mechanical Design / Structural & Multidisciplinary Optimization",
    "type": "学会・専門会議",
    "location": "Busan, Republic of Korea",
    "status": "参加済み",
    "assignment": "中島・松四",
    "purpose": "Busan。構造・形状・トポロジー・複合領域最適化。メカ設計最適化カテゴリの代表実績だが、AI×Robotics全体では補完領域。"
  },
  {
    "id": "20260526-acc-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-05-26",
    "year": 2026,
    "dateLabel": "5月26–29日",
    "name": "ACC 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★☆☆",
    "category": "Control / Motion / Systems",
    "type": "学会・専門会議",
    "location": "Hilton New Orleans Riverside, New Orleans, LA, United States",
    "status": "不参加",
    "assignment": "—",
    "purpose": "American Control Conference。IFAC World Congressを優先し、2026年は不参加"
  },
  {
    "id": "20260527-robotics-summit-and-expo-rse-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-05-27",
    "year": 2026,
    "dateLabel": "5月27–28日",
    "name": "Robotics Summit & Expo (RSE) 2026",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Boston Convention and Exhibition Center, Boston, MA, United States",
    "status": "参加済み",
    "assignment": "村上・佐藤・三浦",
    "purpose": "ロボット開発、商用化、実装・事業化動向 参加済み。"
  },
  {
    "id": "20260528-humanoids-summit-tokyo-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-05-28",
    "year": 2026,
    "dateLabel": "5月28–29日",
    "name": "Humanoids Summit Tokyo 2026",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★★★☆",
    "category": "Robotics / Physical AI本体",
    "type": "技術カンファレンス・サミット",
    "location": "Takanawa Gateway Convention Center, Tokyo, Japan",
    "status": "不参加",
    "assignment": "—",
    "purpose": "国内開催。ヒューマノイド、Embodied AI、商用化、量産、投資・事業化動向を確認する候補。6月末時点で開催済みのため不参加扱い。"
  },
  {
    "id": "20260601-icra-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-06-01",
    "year": 2026,
    "dateLabel": "6月1–5日",
    "name": "ICRA 2026",
    "budgetCandidate": false,
    "importance": "★★★★★",
    "businessFit": "★★★★☆",
    "category": "Robotics / Physical AI本体",
    "type": "学会・専門会議",
    "location": "Vienna, Austria",
    "status": "参加済み",
    "assignment": "村上・佐藤・傳田・岡部",
    "purpose": "Physical AI / Robotics全体動向の主軸 参加済み。"
  },
  {
    "id": "20260603-cvpr-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-06-03",
    "year": 2026,
    "dateLabel": "6月3–7日",
    "name": "CVPR 2026",
    "budgetCandidate": false,
    "importance": "★★★★★",
    "businessFit": "★★★☆☆",
    "category": "Vision / 3D認識",
    "type": "学会・専門会議",
    "location": "Denver, Colorado, United States",
    "status": "参加済み",
    "assignment": "鉢木・田中昌",
    "purpose": "画像認識、3D認識、空間理解、視覚基盤モデル 参加済み。"
  },
  {
    "id": "20260608-london-tech-week-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-06-08",
    "year": 2026,
    "dateLabel": "6月8–12日",
    "name": "London Tech Week 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★☆☆☆",
    "category": "Technology Foresight / Innovation",
    "type": "技術カンファレンス・サミット",
    "location": "Olympia London, London, United Kingdom",
    "status": "不参加",
    "assignment": "—",
    "purpose": "欧州最大級の総合テックフェスティバル。来場者3万人超、エンタープライズAI・DXが主要テーマ。2026年は不参加。"
  },
  {
    "id": "20260615-awe-usa-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-06-15",
    "year": 2026,
    "dateLabel": "6月15–18日",
    "name": "AWE USA 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★☆☆☆",
    "category": "Technology Foresight / Innovation",
    "type": "技術カンファレンス・サミット",
    "location": "Long Beach Convention Center, Long Beach, CA, United States",
    "status": "不参加",
    "assignment": "—",
    "purpose": "XR、Spatial AI、AR/VR、ヒューマンインターフェース、空間コンピューティングの探索候補。6月末時点で開催済みのため不参加扱い。"
  },
  {
    "id": "20260617-vivatech-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-06-17",
    "year": 2026,
    "dateLabel": "6月17–20日",
    "name": "VivaTech 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★☆☆☆",
    "category": "Technology Foresight / Innovation",
    "type": "技術カンファレンス・サミット",
    "location": "Paris Expo Porte de Versailles, Paris, France",
    "status": "参加済み",
    "assignment": "北尾",
    "purpose": "欧州スタートアップ・事業探索 参加済み。"
  },
  {
    "id": "20260622-automate-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-06-22",
    "year": 2026,
    "dateLabel": "6月22–25日",
    "name": "Automate 2026",
    "budgetCandidate": true,
    "importance": "★★★★★",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "McCormick Place, Chicago, IL, United States",
    "status": "参加済み",
    "assignment": "熊谷・橋本翔・田原",
    "purpose": "北米ロボット・自動化・マシンビジョン・モーション 参加済み。"
  },
  {
    "id": "20260628-robomech-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-06-28",
    "year": 2026,
    "dateLabel": "6月28日–7月1日",
    "name": "ROBOMECH 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★★☆☆",
    "category": "Robotics / Physical AI本体",
    "type": "学会・専門会議",
    "location": "福岡国際会議場, Fukuoka, Japan",
    "status": "不参加",
    "assignment": "—",
    "purpose": "国内ロボティクス・メカトロニクス研究、若手発表・育成候補。6月末時点で開催済みのため不参加扱い。"
  },
  {
    "id": "20260706-icml-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-07-06",
    "year": 2026,
    "dateLabel": "7月6–11日",
    "name": "ICML 2026",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★☆☆☆",
    "category": "Robot Learning / AI基盤",
    "type": "学会・専門会議",
    "location": "Seoul, Republic of Korea",
    "status": "不参加",
    "assignment": "—",
    "purpose": "機械学習本流。ICRA / CVPR / CoRLを優先し、2026年は不参加。"
  },
  {
    "id": "20260707-aim-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-07-07",
    "year": 2026,
    "dateLabel": "7月7–11日",
    "name": "AIM 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★☆",
    "category": "Industrial Automation / Smart Factory",
    "type": "学会・専門会議",
    "location": "Genova, Italy",
    "status": "不参加",
    "assignment": "—",
    "purpose": "IEEE/ASME International Conference on Advanced Intelligent Mechatronics。2026年は不参加。"
  },
  {
    "id": "20260712-ifors-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-07-12",
    "year": 2026,
    "dateLabel": "7月12–17日",
    "name": "IFORS 2026",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★★★★",
    "category": "OR / Optimization / Decision Science",
    "type": "学会・専門会議",
    "location": "Vienna, Austria",
    "status": "参加済み",
    "assignment": "北村・熊谷",
    "purpose": "OR、最適化、物流、工程、スケジューリング。参加済み。"
  },
  {
    "id": "20260713-rss-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-07-13",
    "year": 2026,
    "dateLabel": "7月13–17日",
    "name": "RSS 2026",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★★☆☆",
    "category": "Robotics / Physical AI本体",
    "type": "学会・専門会議",
    "location": "Sydney, Australia",
    "status": "参加済み",
    "assignment": "村上",
    "purpose": "ロボティクス分野トップ会議。ICRA参加後の追加深掘り枠として、本会議・Keynote・Workshopを含めて参加済み。部門派遣ではなく、R&Dトップの単独探索枠。"
  },
  {
    "id": "20260719-isfa-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-07-19",
    "year": 2026,
    "dateLabel": "7月19–23日",
    "name": "ISFA 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★★★☆",
    "category": "Industrial Automation / Smart Factory",
    "type": "学会・専門会議",
    "location": "Okayama Convention Center, Okayama, Japan",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "Flexible Automation、製造システム、メカトロ、AI/IoT活用 参加判断対象ではなく、技術・市場動向の参考情報として扱う。"
  },
  {
    "id": "20260719-siggraph-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-07-19",
    "year": 2026,
    "dateLabel": "7月19–23日",
    "name": "SIGGRAPH 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★☆☆",
    "category": "Simulation / Digital Twin / CG",
    "type": "学会・専門会議",
    "location": "Los Angeles Convention Center, Los Angeles, CA, United States",
    "status": "参加予定",
    "assignment": "深川",
    "purpose": "CG、Simulation、3D表現。SIGGRAPH Asiaとの差分確認 参加予定。"
  },
  {
    "id": "20260815-ijcai-ecai-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-08-15",
    "year": 2026,
    "dateLabel": "8月15–21日",
    "name": "IJCAI-ECAI 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★☆☆☆☆",
    "category": "Robot Learning / AI基盤",
    "type": "学会・専門会議",
    "location": "Bremen, Germany",
    "status": "不参加",
    "assignment": "—",
    "purpose": "AI全般の総合会議。計画、推論、マルチエージェント、知識表現などは関連するが、ロボット実機、身体性AI、Sim2Real、ロボット学習が中心ではない。AI×Robotics調査ではCoRL / ICRA / CVPR / GTCを優先するため、2026年は不参加。"
  },
  {
    "id": "20260817-case-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-08-17",
    "year": 2026,
    "dateLabel": "8月17–21日",
    "name": "CASE 2026",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★★★★",
    "category": "Industrial Automation / Smart Factory",
    "type": "学会・専門会議",
    "location": "Shenyang, China",
    "status": "参加予定",
    "assignment": "北村",
    "purpose": "産業自動化、Smart Factory、製造・物流システム"
  },
  {
    "id": "20260819-world-robot-conference-and-expo-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-08-19",
    "year": 2026,
    "dateLabel": "8月19–23日",
    "name": "World Robot Conference and Expo 2026",
    "budgetCandidate": true,
    "importance": "★★★★☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Beijing, China",
    "status": "参加予定",
    "assignment": "保木・渡邊・古谷",
    "purpose": "中国ロボット産業、ヒューマノイド、政策・標準化・社会実装。2026年は保木・渡邊・古谷の3名参加予定。"
  },
  {
    "id": "20260823-ifac-world-congress-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-08-23",
    "year": 2026,
    "dateLabel": "8月23–28日",
    "name": "IFAC World Congress 2026",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★★★★",
    "category": "Control / Motion / Systems",
    "type": "学会・専門会議",
    "location": "Busan, Republic of Korea",
    "status": "参加済み",
    "assignment": "角口・小西",
    "purpose": "制御・モーション・システム基盤。角口・小西が参加。"
  },
  {
    "id": "20260823-asme-idetc-cie-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-08-23",
    "year": 2026,
    "dateLabel": "8月23–26日",
    "name": "ASME IDETC/CIE 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★☆☆☆",
    "category": "Mechanical Design / Structural & Multidisciplinary Optimization",
    "type": "学会・専門会議",
    "location": "Hilton Americas-Houston, Houston, TX, United States",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "設計工学、Design Automation、CIE、メカ設計・最適化の参考情報"
  },
  {
    "id": "20260824-ro-man-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-08-24",
    "year": 2026,
    "dateLabel": "8月24–28日",
    "name": "RO-MAN 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★☆☆",
    "category": "HRI / Human Factors",
    "type": "学会・専門会議",
    "location": "Kitakyushu, Japan",
    "status": "参加済み",
    "assignment": "尾中",
    "purpose": "国内開催。HRI、人協働、受容性、ロボットコミュニケーションを調査。尾中が参加。"
  },
  {
    "id": "20260830-dynamics-and-design-conference-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-08-30",
    "year": 2026,
    "dateLabel": "8月30日–9月2日",
    "name": "Dynamics and Design Conference 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★★★☆",
    "category": "Control / Motion / Systems",
    "type": "学会・専門会議",
    "location": "長良川国際会議場, Gifu, Japan",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "機械力学、計測制御、振動・ダイナミクス、モーション基盤の国内参考情報"
  },
  {
    "id": "20260902-semicon-taiwan-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-09-02",
    "year": 2026,
    "dateLabel": "9月2–4日",
    "name": "SEMICON Taiwan 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "TaiNEX 1&2, Taipei, Taiwan",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "台湾半導体製造装置・材料・プロセス・先端パッケージング 参加判断対象ではなく、技術・市場動向の参考情報として扱う。"
  },
  {
    "id": "20260908-eccv-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-09-08",
    "year": 2026,
    "dateLabel": "9月8–12日",
    "name": "ECCV 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★☆☆☆",
    "category": "Vision / 3D認識",
    "type": "学会・専門会議",
    "location": "Malmö Arena and Malmömässan, Malmö, Sweden",
    "status": "論文・発表追跡",
    "assignment": "—",
    "purpose": "欧州Computer Vision本流。CVPR参加を前提に、ロボットビジョン・3D・空間理解を追跡"
  },
  {
    "id": "20260909-humanoid-robotics-summit-europe-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-09-09",
    "year": 2026,
    "dateLabel": "9月9–11日",
    "name": "Humanoid Robotics Summit Europe 2026",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★★★☆",
    "category": "Robotics / Physical AI本体",
    "type": "技術カンファレンス・サミット",
    "location": "Stuttgart, Germany",
    "status": "参加済み",
    "assignment": "村上・古谷",
    "purpose": "欧州のヒューマノイド、Physical AI、産業実装・企業動向。村上・古谷が参加。"
  },
  {
    "id": "20260914-imts-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-09-14",
    "year": 2026,
    "dateLabel": "9月14–19日",
    "name": "IMTS 2026",
    "budgetCandidate": true,
    "importance": "★★★☆☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "McCormick Place, Chicago, IL, United States",
    "status": "参加済み",
    "assignment": "廣瀬",
    "purpose": "工作機械、製造技術、デジタル製造。廣瀬が参加。"
  },
  {
    "id": "20260915-amb-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-09-15",
    "year": 2026,
    "dateLabel": "9月15–19日",
    "name": "AMB 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Messe Stuttgart, Stuttgart, Germany",
    "status": "参加済み",
    "assignment": "廣瀬・池崎",
    "purpose": "金属加工、工作機械、生産技術。廣瀬・池崎が参加。"
  },
  {
    "id": "20260922-roscon-global-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-09-22",
    "year": 2026,
    "dateLabel": "9月22–24日",
    "name": "ROSCon Global 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★☆",
    "category": "Embedded / Edge / Real-time Systems",
    "type": "技術カンファレンス・サミット",
    "location": "Toronto, Canada",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "ROS開発者カンファレンス。ロボット実装基盤・OSS・開発者コミュニティの参考情報"
  },
  {
    "id": "20260927-iros-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-09-27",
    "year": 2026,
    "dateLabel": "9月27日–10月1日",
    "name": "IROS 2026",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★★★☆",
    "category": "Robotics / Physical AI本体",
    "type": "学会・専門会議",
    "location": "Pittsburgh, Pennsylvania, United States",
    "status": "参加予定",
    "assignment": "酒井・羽山",
    "purpose": "知能ロボット・ロボットシステムの分野トップ会議。酒井・羽山が参加し、内容をR&D内で共有する予定。"
  },
  {
    "id": "20261004-smc-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-10-04",
    "year": 2026,
    "dateLabel": "10月4–7日",
    "name": "SMC 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★☆☆",
    "category": "HRI / Human Factors",
    "type": "学会・専門会議",
    "location": "Bellevue, WA, United States",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "IEEE International Conference on Systems, Man, and Cybernetics。人間機械系、システム、サイバネティクスの参考情報"
  },
  {
    "id": "20261005-world-summit-ai-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-10-05",
    "year": 2026,
    "dateLabel": "10月5–9日",
    "name": "World Summit AI 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★☆☆☆☆",
    "category": "Technology Foresight / Innovation",
    "type": "技術カンファレンス・サミット",
    "location": "Amsterdam, Netherlands",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "AI企業・政策・スタートアップ・社会実装トレンドの探索参考情報"
  },
  {
    "id": "20261006-vision-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-10-06",
    "year": 2026,
    "dateLabel": "10月6–8日",
    "name": "VISION 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★☆",
    "category": "Vision / 3D認識",
    "type": "展示会・見本市",
    "location": "Messe Stuttgart, Stuttgart, Germany",
    "status": "参加予定",
    "assignment": "橋本将",
    "purpose": "マシンビジョン、画像処理、産業用カメラ・検査の展示会参加予定。部門予算化候補には含めない。"
  },
  {
    "id": "20261013-semicon-west-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-10-13",
    "year": 2026,
    "dateLabel": "10月13–15日",
    "name": "SEMICON West 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Moscone Center, San Francisco, CA, United States",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "北米半導体製造装置・材料・プロセス・先端パッケージング 参加判断対象ではなく、技術・市場動向の参考情報として扱う。"
  },
  {
    "id": "20261018-iecon-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-10-18",
    "year": 2026,
    "dateLabel": "10月18–21日",
    "name": "IECON 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★★☆☆",
    "category": "Industrial Automation / Smart Factory",
    "type": "学会・専門会議",
    "location": "Doha, Qatar",
    "status": "不参加",
    "assignment": "—",
    "purpose": "Industrial Electronics全般。2026年は不参加。"
  },
  {
    "id": "20261020-techex-europe-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-10-20",
    "year": 2026,
    "dateLabel": "10月20–21日",
    "name": "TechEx Europe 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★☆☆☆",
    "category": "Technology Foresight / Innovation",
    "type": "技術カンファレンス・サミット",
    "location": "RAI Amsterdam, Amsterdam, Netherlands",
    "status": "候補",
    "assignment": "TBD",
    "purpose": "IoT、AI、Edge、デジタル基盤"
  },
  {
    "id": "20261020-euroblech-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-10-20",
    "year": 2026,
    "dateLabel": "10月20–23日",
    "name": "EuroBLECH 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Hanover Fairground, Hannover, Germany",
    "status": "参加予定",
    "assignment": "村上・金築・美馬",
    "purpose": "板金加工、レーザ、成形、加工自動化。参加予定。"
  },
  {
    "id": "20261025-mecc-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-10-25",
    "year": 2026,
    "dateLabel": "10月25–28日",
    "name": "MECC 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★☆☆",
    "category": "Control / Motion / Systems",
    "type": "学会・専門会議",
    "location": "Phoenix, AZ, United States",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "Modeling, Estimation and Control。動的システムのモデリング・推定・制御参考情報"
  },
  {
    "id": "20261026-jimtof-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-10-26",
    "year": 2026,
    "dateLabel": "10月26–31日",
    "name": "JIMTOF 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Tokyo Big Sight, Tokyo, Japan",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "工作機械、加工、計測、製造技術の国内大型展示会参考情報"
  },
  {
    "id": "20261101-informs-annual-meeting-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-11-01",
    "year": 2026,
    "dateLabel": "11月1–4日",
    "name": "INFORMS Annual Meeting 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★★☆☆",
    "category": "OR / Optimization / Decision Science",
    "type": "学会・専門会議",
    "location": "San Francisco, CA, United States",
    "status": "不参加",
    "assignment": "—",
    "purpose": "OR/MS/Analytics。IFORS後に必要性判断"
  },
  {
    "id": "20261103-cemat-asia-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-11-03",
    "year": 2026,
    "dateLabel": "11月3–6日",
    "name": "CeMAT ASIA 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Shanghai New International Expo Centre, Shanghai, China",
    "status": "候補",
    "assignment": "TBD",
    "purpose": "中国・アジアの物流・倉庫自動化市場"
  },
  {
    "id": "20261109-corl-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-11-09",
    "year": 2026,
    "dateLabel": "11月9–12日",
    "name": "CoRL 2026",
    "budgetCandidate": false,
    "importance": "★★★★★",
    "businessFit": "★★★☆☆",
    "category": "Robot Learning / AI基盤",
    "type": "学会・専門会議",
    "location": "Austin, Texas, United States",
    "status": "参加予定",
    "assignment": "熊谷・佐藤元",
    "purpose": "Robot Learning、VLA、Sim2Real、基盤モデル"
  },
  {
    "id": "20261110-semicon-europa-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-11-10",
    "year": 2026,
    "dateLabel": "11月10–13日",
    "name": "SEMICON Europa 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Trade Fair Center Messe München, Munich, Germany",
    "status": "候補",
    "assignment": "TBD",
    "purpose": "欧州半導体製造装置・材料・プロセス。electronica併催"
  },
  {
    "id": "20261110-electronica-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-11-10",
    "year": 2026,
    "dateLabel": "11月10–13日",
    "name": "electronica 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Trade Fair Center Messe München, Munich, Germany",
    "status": "参加予定",
    "assignment": "寺田・三枝",
    "purpose": "半導体、パッシブ部品、組込みシステム、パワーエレクトロニクス等、電子部品・技術全般を扱う世界最大級の電子部品展示会。SEMICON Europa 2026と同日程・同会場で併催。寺田・三枝が参加予定。"
  },
  {
    "id": "20261117-formnext-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-11-17",
    "year": 2026,
    "dateLabel": "11月17–20日",
    "name": "Formnext 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Frankfurt Fair & Exhibition Centre, Frankfurt am Main, Germany",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "アディティブマニュファクチャリング、工業用3Dプリンティング、次世代製造技術の参考情報。"
  },
  {
    "id": "20261120-itma-asia-citme-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-11-20",
    "year": 2026,
    "dateLabel": "11月20–24日",
    "name": "ITMA ASIA + CITME 2026",
    "budgetCandidate": true,
    "importance": "★★☆☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "National Exhibition and Convention Center, Shanghai, China",
    "status": "候補",
    "assignment": "TBD",
    "purpose": "繊維機械・繊維製造技術"
  },
  {
    "id": "20261124-sps-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-11-24",
    "year": 2026,
    "dateLabel": "11月24–26日",
    "name": "SPS 2026",
    "budgetCandidate": true,
    "importance": "★★★☆☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Nuremberg, Germany",
    "status": "参加予定",
    "assignment": "東・1名",
    "purpose": "Smart Production Solutions。FA、産業制御、産業通信、ドライブ、センサ等を確認する。東が1名で参加予定。"
  },
  {
    "id": "20261201-siggraph-asia-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-12-01",
    "year": 2026,
    "dateLabel": "12月1–4日",
    "name": "SIGGRAPH Asia 2026",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★★★☆",
    "category": "Simulation / Digital Twin / CG",
    "type": "学会・専門会議",
    "location": "KLCC, Kuala Lumpur, Malaysia",
    "status": "参加予定",
    "assignment": "村上",
    "purpose": "Digital Twin、Simulation、3D表現、生成表現"
  },
  {
    "id": "20261203-ros-industrial-conference-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-12-03",
    "year": 2026,
    "dateLabel": "12月3–4日",
    "name": "ROS-Industrial Conference 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★☆",
    "category": "Embedded / Edge / Real-time Systems",
    "type": "技術カンファレンス・サミット",
    "location": "Fraunhofer IPA, Stuttgart, Germany",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "ROS-Industrial。産業ロボット実装、OSS、システムインテグレーションの参考情報"
  },
  {
    "id": "20261206-humanoids-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-12-06",
    "year": 2026,
    "dateLabel": "12月6–9日",
    "name": "Humanoids 2026",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★★☆☆",
    "category": "Robotics / Physical AI本体",
    "type": "学会・専門会議",
    "location": "Santa Clara, California, United States",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "ヒューマノイド、全身制御、身体性AIの主要専門会議。AI×Robotics / Physical AI観点では重要だが、2026年の参加者はTBD。 参加判断対象ではなく、技術・市場動向の参考情報として扱う。"
  },
  {
    "id": "20261206-neurips-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-12-06",
    "year": 2026,
    "dateLabel": "12月6–12日",
    "name": "NeurIPS 2026",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★☆☆☆",
    "category": "Robot Learning / AI基盤",
    "type": "学会・専門会議",
    "location": "Sydney / Atlanta / Paris",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "AI基盤のトップ会議。現地参加せず、Embodied AI / World Model / Robotics関連Workshopと論文を追跡 参加判断対象ではなく、技術・市場動向の参考情報として扱う。"
  },
  {
    "id": "20261207-gitex-global-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-12-07",
    "year": 2026,
    "dateLabel": "12月7–11日",
    "name": "GITEX Global 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★☆☆☆",
    "category": "Technology Foresight / Innovation",
    "type": "技術カンファレンス・サミット",
    "location": "Dubai Exhibition Centre, Expo City Dubai, UAE",
    "status": "候補",
    "assignment": "TBD",
    "purpose": "AI、デジタル、スタートアップ、市場探索"
  },
  {
    "id": "20261209-semicon-japan-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-12-09",
    "year": 2026,
    "dateLabel": "12月9–11日",
    "name": "SEMICON Japan 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Tokyo Big Sight, Tokyo, Japan",
    "status": "候補",
    "assignment": "TBD",
    "purpose": "国内半導体製造装置・材料・先端パッケージング・検査計測"
  },
  {
    "id": "20261215-cdc-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-12-15",
    "year": 2026,
    "dateLabel": "12月15–18日",
    "name": "CDC 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★☆☆",
    "category": "Control / Motion / Systems",
    "type": "学会・専門会議",
    "location": "Hilton Hawaiian Village, Honolulu, HI, United States",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "IEEE Conference on Decision and Control。制御理論・意思決定・最適制御。2026年は不参加 参加判断対象ではなく、技術・市場動向の参考情報として扱う。"
  },
  {
    "id": "20270106-ces-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-01-06",
    "year": 2027,
    "dateLabel": "1月6–9日",
    "name": "CES 2027",
    "budgetCandidate": true,
    "importance": "★★☆☆☆",
    "businessFit": "★★☆☆☆",
    "category": "Technology Foresight / Innovation",
    "type": "技術カンファレンス・サミット",
    "location": "Las Vegas, Nevada, United States",
    "status": "2027計画",
    "assignment": "TBD",
    "purpose": "広域技術・事業探索"
  },
  {
    "id": "20270120-humanoid-evolution-summit-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-01-20",
    "year": 2027,
    "dateLabel": "1月20–21日",
    "name": "Humanoid Evolution Summit 2027",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★☆☆",
    "category": "Robotics / Physical AI本体",
    "type": "技術カンファレンス・サミット",
    "location": "Munich, Germany",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "欧州のヒューマノイド、Physical AI、Digital Twin、産業実装・事業化動向を部門で把握する参考情報。2027年が初開催のため、参加はプログラム・登壇企業・展示内容の具体化後に判断する。"
  },
  {
    "id": "20270209-md-and-m-west-2027-automation-sector-atx-west",
    "dateStatus": "confirmed",
    "sortDate": "2027-02-09",
    "year": 2027,
    "dateLabel": "2月9–11日",
    "name": "MD&M West 2027（Automation Sector／旧ATX West）",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★★☆☆",
    "category": "Industrial Automation / Smart Factory",
    "type": "展示会・見本市",
    "location": "Anaheim Convention Center, Anaheim, CA, United States",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "Automation、ロボティクス、センサ、Motion Control、製造技術を扱うMD&M West内の展示分野。Automate、ProMat等との重複を踏まえ、北米西海岸の製造・MedTech・包装分野を含む市場動向の参考情報として管理する。"
  },
  {
    "id": "20270217-semicon-korea-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-02-17",
    "year": 2027,
    "dateLabel": "2月17–19日",
    "name": "SEMICON Korea 2027",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★★☆☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "COEXほか, Seoul, Republic of Korea",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "半導体装置・材料・プロセス。COEX全館に加え、Westin Seoul ParnasとGrand InterContinental Seoul Parnasで開催。",
    "sourceUrl": "https://www.semiconkorea.org/",
    "verifiedAt": "2026-09-16"
  },
  {
    "id": "20270301-mwc-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-03-01",
    "year": 2027,
    "dateLabel": "3月1–4日",
    "name": "MWC 2027",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★☆☆☆",
    "category": "Technology Foresight / Innovation",
    "type": "技術カンファレンス・サミット",
    "location": "Fira Barcelona Gran Via, Barcelona, Spain",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "通信・エッジ・AI/IoT基盤。部門の参加・予算計画には含めず、関連する市場・技術動向の参考情報として管理する。"
  },
  {
    "id": "20270302-jec-world-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-03-02",
    "year": 2027,
    "dateLabel": "3月2–4日",
    "name": "JEC World 2027",
    "budgetCandidate": true,
    "importance": "★★☆☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Paris Nord Villepinte, France",
    "status": "2027計画",
    "assignment": "TBD",
    "purpose": "複合材料"
  },
  {
    "id": "20270314-gtc-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-03-14",
    "year": 2027,
    "dateLabel": "3月14–18日",
    "name": "GTC 2027",
    "budgetCandidate": true,
    "importance": "★★★★★",
    "businessFit": "★★★★☆",
    "category": "Technology Foresight / Innovation",
    "type": "技術カンファレンス・サミット",
    "location": "San Jose McEnery Convention Center and venues throughout San Jose, CA, United States",
    "status": "2027計画",
    "assignment": "1名",
    "purpose": "Physical AI、AI/GPU、ロボティクス基盤、Omniverse、シミュレーション、Edge AIの最重要候補。NVIDIA公式FAQでは全日程を3月14–18日、公式トップ／イベント一覧では本会議を3月15–18日と案内。",
    "dateNote": "本会議：15–18日"
  },
  {
    "id": "20270316-logimat-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-03-16",
    "year": 2027,
    "dateLabel": "3月16–18日",
    "name": "LogiMAT 2027",
    "budgetCandidate": true,
    "importance": "★★★☆☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Messe Stuttgart, Stuttgart, Germany",
    "status": "2027計画",
    "assignment": "～2名",
    "purpose": "物流・倉庫自動化"
  },
  {
    "id": "20270316-embedded-world-germany-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-03-16",
    "year": 2027,
    "dateLabel": "3月16–18日",
    "name": "embedded world Germany 2027",
    "budgetCandidate": true,
    "importance": "★★★☆☆",
    "businessFit": "★★★★☆",
    "category": "Embedded / Edge / Real-time Systems",
    "type": "展示会・見本市",
    "location": "Exhibition Centre Nuremberg, Nuremberg, Germany",
    "status": "2027計画",
    "assignment": "TBD",
    "purpose": "組込み、Edge AI、リアルタイム、機能安全、Embedded Vision。部門予算化計画。GTC 2027およびLogiMAT 2027と日程が重なるため別担当を前提に検討する。"
  },
  {
    "id": "20270330-semicon-west-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-03-30",
    "year": 2027,
    "dateLabel": "3月30日–4月1日",
    "name": "SEMICON West 2027",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Phoenix Convention Center, Phoenix, AZ, United States",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "北米半導体装置・材料・プロセス。2027年から春開催へ移行し、Phoenixを長期開催地とする。",
    "sourceUrl": "https://semiconwest.org/news-press/press-releases",
    "verifiedAt": "2026-09-16"
  },
  {
    "id": "20270405-hannover-messe-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-04-05",
    "year": 2027,
    "dateLabel": "4月5–8日",
    "name": "Hannover Messe 2027",
    "budgetCandidate": true,
    "importance": "★★★☆☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Hannover Exhibition Grounds, Hannover, Germany",
    "status": "2027計画",
    "assignment": "～2名",
    "purpose": "総合産業・FA"
  },
  {
    "id": "20270419-promat-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-04-19",
    "year": 2027,
    "dateLabel": "4月19–21日",
    "name": "ProMat 2027",
    "budgetCandidate": true,
    "importance": "★★★★☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "McCormick Place, Chicago, IL, United States",
    "status": "2027計画",
    "assignment": "～2名",
    "purpose": "物流・マテハン・サプライチェーン"
  },
  {
    "id": "20270510-automate-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-05-10",
    "year": 2027,
    "dateLabel": "5月10–13日",
    "name": "Automate 2027",
    "budgetCandidate": true,
    "importance": "★★★★★",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Las Vegas Convention Center, Las Vegas, NV, United States",
    "status": "2027計画",
    "assignment": "2名",
    "purpose": "北米最大級のロボット・自動化展示会。2027年はLas Vegas開催。部門予算化候補。"
  },
  {
    "id": "20270524-icra-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-05-24",
    "year": 2027,
    "dateLabel": "5月24–28日",
    "name": "ICRA 2027",
    "budgetCandidate": false,
    "importance": "★★★★★",
    "businessFit": "★★★★☆",
    "category": "Robotics / Physical AI本体",
    "type": "学会・専門会議",
    "location": "COEX, Seoul, Republic of Korea",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "Robotics代表会議。部門の参加・予算計画には含めず、論文・発表と個別参加判断の参考情報として管理する。"
  },
  {
    "id": "20270525-semicon-southeast-asia-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-05-25",
    "year": 2027,
    "dateLabel": "5月25–27日",
    "name": "SEMICON Southeast Asia 2027",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "MITEC, Kuala Lumpur, Malaysia",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "東南アジア半導体装置・材料・プロセス。Malaysia International Trade and Exhibition Centreで開催。",
    "sourceUrl": "https://www.semiconsea.org/Event-Overview",
    "verifiedAt": "2026-09-16"
  },
  {
    "id": "20270602-robotics-summit-and-expo-rse-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-06-02",
    "year": 2027,
    "dateLabel": "6月2–3日",
    "name": "Robotics Summit & Expo (RSE) 2027",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★★★☆",
    "category": "Robotics / Physical AI本体",
    "type": "技術カンファレンス・サミット",
    "location": "Boston, MA, United States",
    "status": "2027計画",
    "assignment": "1名",
    "purpose": "商用ロボット開発・実装寄りの技術カンファレンス／Expo。2027年6月2–3日、Boston開催を公式サイトで確認済み。"
  },
  {
    "id": "20270607-london-tech-week-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-06-07",
    "year": 2027,
    "dateLabel": "6月7–11日",
    "name": "London Tech Week 2027",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★☆☆☆",
    "category": "Technology Foresight / Innovation",
    "type": "技術カンファレンス・サミット",
    "location": "Olympia London, London, United Kingdom",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "欧州最大級の総合テックフェスティバル。エンタープライズAI・DX・スタートアップ動向の探索候補として参考情報で管理。"
  },
  {
    "id": "20270620-cvpr-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-06-20",
    "year": 2027,
    "dateLabel": "6月20–25日",
    "name": "CVPR 2027",
    "budgetCandidate": false,
    "importance": "★★★★★",
    "businessFit": "★★★☆☆",
    "category": "Vision / 3D認識",
    "type": "学会・専門会議",
    "location": "Seattle, Washington, United States",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "画像認識、3D認識、空間理解、視覚基盤モデル。専用公式サイトは6月20–25日、CVF公式一覧は6月20–24日と案内が分かれるため、専用サイトの期間を採用。",
    "sourceUrl": "https://cvpr.thecvf.com/",
    "verifiedAt": "2026-09-16"
  },
  {
    "id": "20270622-automatica-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-06-22",
    "year": 2027,
    "dateLabel": "6月22–25日",
    "name": "automatica 2027",
    "budgetCandidate": true,
    "importance": "★★★★☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Messe München, Munich, Germany",
    "status": "2027計画",
    "assignment": "1名",
    "purpose": "スマートオートメーション・ロボティクス"
  },
  {
    "id": "20270706-rss-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-07-06",
    "year": 2027,
    "dateLabel": "7月6–11日",
    "name": "RSS 2027",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★★☆☆",
    "category": "Robotics / Physical AI本体",
    "type": "学会・専門会議",
    "location": "Athens, Greece",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "ロボティクス分野トップ会議。2027年7月6–11日、Athens開催。部門の参加・予算計画には含めず、論文・発表と個別参加判断の参考情報として管理する。"
  },
  {
    "id": "20270808-siggraph-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-08-08",
    "year": 2027,
    "dateLabel": "8月8–12日",
    "name": "SIGGRAPH 2027",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★☆☆",
    "category": "Simulation / Digital Twin / CG",
    "type": "学会・専門会議",
    "location": "Anaheim, California, United States",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "Computer Graphics、Simulation、Digital Twin、3D表現、生成表現、XR。部門予算化はせず、Physical AIのシミュレーション・デジタル環境側を把握する参考情報として管理する。"
  },
  {
    "id": "20270916-itma-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-09-16",
    "year": 2027,
    "dateLabel": "9月16–22日",
    "name": "ITMA 2027",
    "budgetCandidate": true,
    "importance": "★★☆☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Hannover Exhibition Center, Hannover, Germany",
    "status": "2027計画",
    "assignment": "前半：～2名／後半：～2名",
    "purpose": "繊維機械・繊維製造。会期前半・後半で担当を分けて派遣する。"
  },
  {
    "id": "20270926-iros-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-09-26",
    "year": 2027,
    "dateLabel": "9月26日–10月1日",
    "name": "IROS 2027",
    "budgetCandidate": false,
    "importance": "★★★★★",
    "businessFit": "★★★★☆",
    "category": "Robotics / Physical AI本体",
    "type": "学会・専門会議",
    "location": "Fortezza da Basso, Florence, Italy",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "知能ロボット・ロボットシステムの分野トップ会議。部門予算化はせず、論文・発表と個別参加判断の参考情報として管理する。"
  },
  {
    "id": "20271002-iccv-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-10-02",
    "year": 2027,
    "dateLabel": "10月2–8日",
    "name": "ICCV 2027",
    "budgetCandidate": false,
    "importance": "★★★★★",
    "businessFit": "★★★☆☆",
    "category": "Vision / 3D認識",
    "type": "学会・専門会議",
    "location": "Hong Kong",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "画像認識、3D認識、視覚基盤モデル。CVPR・ECCVと並ぶComputer Visionのトップティア会議として、論文・発表を追跡する。",
    "sourceUrl": "https://www.thecvf.com/?p=137",
    "verifiedAt": "2026-09-16"
  },
  {
    "id": "20271004-emo-milano-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-10-04",
    "year": 2027,
    "dateLabel": "10月4–9日",
    "name": "EMO Milano 2027",
    "budgetCandidate": true,
    "importance": "★★☆☆☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Fieramilano, Milan, Italy",
    "status": "2027計画",
    "assignment": "～2名",
    "purpose": "工作機械・金属加工"
  },
  {
    "id": "20271026-formnext-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-10-26",
    "year": 2027,
    "dateLabel": "10月26–29日",
    "name": "Formnext 2027",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Frankfurt Fair & Exhibition Centre, Frankfurt am Main, Germany",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "アディティブマニュファクチャリング、工業用3Dプリンティング、材料、次世代製造技術。部門の参加・予算計画には含めず、関連テーマの参考情報として管理する。"
  },
  {
    "id": "20271116-semicon-europa-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-11-16",
    "year": 2027,
    "dateLabel": "11月16–19日",
    "name": "SEMICON Europa 2027",
    "budgetCandidate": true,
    "importance": "★★☆☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Trade Fair Center Messe München, Munich, Germany",
    "status": "2027計画",
    "assignment": "TBD",
    "purpose": "欧州半導体装置・材料・プロセス。部門予算化計画。"
  },
  {
    "id": "20271123-sps-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-11-23",
    "year": 2027,
    "dateLabel": "11月23–25日",
    "name": "SPS 2027",
    "budgetCandidate": true,
    "importance": "★★★☆☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Exhibition Centre Nuremberg, Nuremberg, Germany",
    "status": "2027計画",
    "assignment": "～2名",
    "purpose": "Smart Production Solutions。FA、PLC、産業制御、産業通信、ドライブ、センサ、Industrial AIを確認する基幹候補。"
  },
  {
    "id": "20271130-siggraph-asia-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-11-30",
    "year": 2027,
    "dateLabel": "11月30日–12月3日",
    "name": "SIGGRAPH Asia 2027",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★★★☆",
    "category": "Simulation / Digital Twin / CG",
    "type": "学会・専門会議",
    "location": "Tokyo International Forum, Tokyo, Japan",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "Computer Graphics、Simulation、Digital Twin、3D表現、生成表現。2027年は東京開催。",
    "sourceUrl": "https://asia.siggraph.org/2026/about-the-event/siggraph-asia-2027/",
    "verifiedAt": "2026-09-16"
  },
  {
    "id": "20280403-modex-2028",
    "dateStatus": "confirmed",
    "sortDate": "2028-04-03",
    "year": 2028,
    "dateLabel": "4月3–5日",
    "name": "MODEX 2028",
    "budgetCandidate": true,
    "importance": "★★★☆☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Georgia World Congress Center, Atlanta, GA, United States",
    "status": "2028計画",
    "assignment": "TBD",
    "purpose": "ProMat 2027と相互補完で見る物流・マテハン・サプライチェーン展示会。",
    "sourceUrl": "https://www.modexshow.com/",
    "verifiedAt": "2026-09-16"
  },
  {
    "id": "20280404-interclean-amsterdam-2028",
    "dateStatus": "confirmed",
    "sortDate": "2028-04-04",
    "year": 2028,
    "dateLabel": "4月4–7日",
    "name": "Interclean Amsterdam 2028",
    "budgetCandidate": true,
    "importance": "★★☆☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "RAI Amsterdam, Amsterdam, Netherlands",
    "status": "2028計画",
    "assignment": "TBD",
    "purpose": "清掃・衛生・サービスロボット・施設管理の業界実装確認。Interclean Amsterdamの次回開催として管理。"
  },
  {
    "id": "20281018-k-du-sseldorf-2028",
    "dateStatus": "confirmed",
    "sortDate": "2028-10-18",
    "year": 2028,
    "dateLabel": "10月18–25日",
    "name": "K Düsseldorf 2028",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Messe Düsseldorf, Düsseldorf, Germany",
    "status": "2028計画",
    "assignment": "TBD",
    "purpose": "プラスチック・ゴム、材料、成形加工、リサイクル、材料循環の大型展示会"
  },
  {
    "id": "pending-euroblech-2028",
    "dateStatus": "pending",
    "order": 0,
    "name": "EuroBLECH 2028",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "handling": "2028候補：TBD",
    "assignment": "TBD",
    "location": "Hanover Fairground, Hannover, Germany（想定）",
    "purpose": "板金加工、レーザ、成形、加工自動化。隔年開催のためEuroBLECHの次回開催として管理。"
  },
  {
    "id": "pending-semicon-japan-2027",
    "dateStatus": "pending",
    "order": 1,
    "name": "SEMICON Japan 2027",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "handling": "2027候補：TBD",
    "assignment": "TBD",
    "location": "TBD",
    "purpose": "国内半導体装置・材料・プロセス。日程・場所はTBD"
  },
  {
    "id": "pending-corl-2027",
    "dateStatus": "pending",
    "order": 2,
    "name": "CoRL 2027",
    "budgetCandidate": false,
    "importance": "★★★★★",
    "businessFit": "★★★☆☆",
    "category": "Robot Learning / AI基盤",
    "handling": "2027候補：日程TBD",
    "assignment": "TBD",
    "location": "TBD",
    "purpose": "Robot Learning、VLA、Sim2Real、基盤モデルの中核会議。公式日程・開催地の発表後に5章へ移す。"
  },
  {
    "id": "pending-world-robot-conference-and-expo-2027",
    "dateStatus": "pending",
    "order": 3,
    "name": "World Robot Conference and Expo 2027",
    "budgetCandidate": true,
    "importance": "★★★★☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "handling": "2027候補：8月18日開幕／終了日TBD",
    "assignment": "TBD",
    "location": "Beijing, China（開催地未確認）",
    "purpose": "中国ロボット産業、ヒューマノイド、政策・標準化・社会実装。公式発表で2027年8月18日の開幕を確認。終了日と会場の発表後に5章へ移す。",
    "sourceUrl": "https://www.worldrobotconference.com/news/3616.html",
    "verifiedAt": "2026-09-16"
  },
  {
    "id": "pending-humanoid-robotics-summit-europe-2027",
    "dateStatus": "pending",
    "order": 4,
    "name": "Humanoid Robotics Summit Europe 2027",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★★★☆",
    "category": "Robotics / Physical AI本体",
    "handling": "2027候補：日程TBD",
    "assignment": "TBD",
    "location": "Stuttgart, Germany（想定）",
    "purpose": "欧州のヒューマノイド、Physical AI、産業実装・企業動向。2026年参加実績を踏まえ、公式日程発表後に5章へ移す。"
  },
  {
    "id": "pending-roscon-global-2027",
    "dateStatus": "pending",
    "order": 5,
    "name": "ROSCon Global 2027",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★☆",
    "category": "Embedded / Edge / Real-time Systems",
    "handling": "2027候補：日程TBD",
    "assignment": "TBD",
    "location": "TBD",
    "purpose": "ROS 2、ロボット実装基盤、OSS、開発ツール、シミュレーション連携。公式日程・開催地の発表待ち。"
  },
  {
    "id": "pending-icml-2027",
    "dateStatus": "pending",
    "order": 6,
    "name": "ICML 2027",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★☆☆☆",
    "category": "Robot Learning / AI基盤",
    "handling": "2027論文・発表追跡：TBD",
    "assignment": "TBD",
    "location": "South America（都市TBD）",
    "purpose": "機械学習本流。現地参加よりEmbodied AI、World Model、Robotics関連の論文・Workshop追跡を基本とし、日程・都市の公式発表後に再評価する。",
    "sourceUrl": "https://icml.cc/Conferences/FutureMeetings",
    "verifiedAt": "2026-09-16"
  },
  {
    "id": "pending-neurips-2027",
    "dateStatus": "pending",
    "order": 7,
    "name": "NeurIPS 2027",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★☆☆☆",
    "category": "Robot Learning / AI基盤",
    "handling": "2027論文・発表追跡：TBD",
    "assignment": "TBD",
    "location": "Europe",
    "purpose": "AI基盤のトップ会議。Embodied AI、World Model、Robotics関連Workshopと論文を追跡する。公式発表は欧州開催まで。"
  },
  {
    "id": "pending-item",
    "dateStatus": "pending",
    "order": 8,
    "name": "年間予算予備枠（部門）",
    "budgetCandidate": true,
    "importance": "—",
    "businessFit": "—",
    "category": "部門予算枠",
    "handling": "2027年度年間枠",
    "assignment": "予備枠10名分",
    "location": "—",
    "purpose": "特定イベントに紐づけない追加派遣・追加調査用の年間予算予備枠。WRC固有の人数ではない。"
  }
];
