// Physical AI関連イベントの正本データ。表示は physical_ai_events_overview.html が担当する。
window.PHYSICAL_AI_EVENTS = [
  {
    "id": "20260106-ces-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-01-06",
    "year": 2026,
    "dateLabel": "1月6–9日",
    "name": "CES 2026",
    "budgetCandidate": true,
    "importance": "★★☆☆☆",
    "businessFit": "★★☆☆☆",
    "category": "Technology Foresight / Innovation",
    "type": "技術カンファレンス・サミット",
    "location": "Las Vegas, Nevada, United States",
    "status": "参加済み",
    "assignment": "長澤・西田・傳田",
    "purpose": "技術探索・事業探索・スタートアップ探索枠"
  },
  {
    "id": "20260120-aaai-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-01-20",
    "year": 2026,
    "dateLabel": "1月20–27日",
    "name": "AAAI 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★☆☆☆☆",
    "category": "Robot Learning / AI基盤",
    "type": "学会・専門会議",
    "location": "Singapore EXPO, Singapore",
    "status": "不参加",
    "assignment": "—",
    "purpose": "AI全般の総合会議。推論、探索、計画、知識表現、機械学習応用などは含むが、ロボット実機、身体性AI、Sim2Real、ロボット学習が会議全体の主題ではない。AI×Robotics調査ではCoRL / ICRA / CVPR / GTCを優先するため、2026年は不参加。"
  },
  {
    "id": "20260211-semicon-korea-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-02-11",
    "year": 2026,
    "dateLabel": "2月11–13日",
    "name": "SEMICON Korea 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★★☆☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "COEX, Seoul, Republic of Korea",
    "status": "不参加",
    "assignment": "—",
    "purpose": "半導体製造装置・材料・プロセス・先端パッケージング。不参加。"
  },
  {
    "id": "20260309-amc-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-03-09",
    "year": 2026,
    "dateLabel": "3月9–11日",
    "name": "AMC 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★☆",
    "category": "Control / Motion / Systems",
    "type": "学会・専門会議",
    "location": "Daegu, Republic of Korea",
    "status": "参加済み",
    "assignment": "橋本・田端",
    "purpose": "Advanced Motion Control。制御・モーション基盤の補完実績。小規模専門会議として1名程度の参加で十分。"
  },
  {
    "id": "20260310-jec-world-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-03-10",
    "year": 2026,
    "dateLabel": "3月10–12日",
    "name": "JEC World 2026",
    "budgetCandidate": true,
    "importance": "★★☆☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Paris-Nord Villepinte, France",
    "status": "参加済み",
    "assignment": "仲西・谷川・渡辺",
    "purpose": "複合材料、軽量化、材料加工・産業応用"
  },
  {
    "id": "20260310-embedded-world-germany-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-03-10",
    "year": 2026,
    "dateLabel": "3月10–12日",
    "name": "embedded world Germany 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★☆",
    "category": "Embedded / Edge / Real-time Systems",
    "type": "展示会・見本市",
    "location": "Nuremberg, Germany",
    "status": "不参加",
    "assignment": "—",
    "purpose": "組込み、エッジAI、リアルタイム、機能安全、産業用コンピューティングの実装基盤として重要。ただし2026年は不参加。"
  },
  {
    "id": "20260312-sxsw-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-03-12",
    "year": 2026,
    "dateLabel": "3月12–18日",
    "name": "SXSW 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★☆☆☆☆",
    "category": "Technology Foresight / Innovation",
    "type": "技術カンファレンス・サミット",
    "location": "Austin, Texas, United States",
    "status": "参加済み",
    "assignment": "尾中",
    "purpose": "技術探索・事業探索・社会実装トレンド"
  },
  {
    "id": "20260316-gtc-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-03-16",
    "year": 2026,
    "dateLabel": "3月16–19日",
    "name": "GTC 2026",
    "budgetCandidate": true,
    "importance": "★★★★★",
    "businessFit": "★★★★☆",
    "category": "Technology Foresight / Innovation",
    "type": "技術カンファレンス・サミット",
    "location": "San Jose McEnery Convention Center, San Jose, CA, United States",
    "status": "不参加",
    "assignment": "—",
    "purpose": "NVIDIA GTC。Physical AI、AI基盤、GPU、ロボティクス基盤、シミュレーション、Omniverse、Edge AIの観点で極めて重要。ただし2026年は不参加。"
  },
  {
    "id": "20260316-hri-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-03-16",
    "year": 2026,
    "dateLabel": "3月16–19日",
    "name": "HRI 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★☆☆☆",
    "category": "HRI / Human Factors",
    "type": "学会・専門会議",
    "location": "Edinburgh, United Kingdom",
    "status": "不参加",
    "assignment": "—",
    "purpose": "人協働・受容性・Human-Robot Interaction。後追い対象"
  },
  {
    "id": "20260320-3dv-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-03-20",
    "year": 2026,
    "dateLabel": "3月20–23日",
    "name": "3DV 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★☆☆",
    "category": "Vision / 3D認識",
    "type": "学会・専門会議",
    "location": "Vancouver Convention Centre, Vancouver, BC, Canada",
    "status": "不参加",
    "assignment": "—",
    "purpose": "3D Vision。3D認識・空間理解の補完候補。不参加。"
  },
  {
    "id": "20260324-logimat-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-03-24",
    "year": 2026,
    "dateLabel": "3月24–26日",
    "name": "LogiMAT 2026",
    "budgetCandidate": true,
    "importance": "★★★☆☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Messe Stuttgart, Stuttgart, Germany",
    "status": "参加済み",
    "assignment": "榎・鉢木",
    "purpose": "欧州物流・倉庫自動化"
  },
  {
    "id": "20260325-semicon-china-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-03-25",
    "year": 2026,
    "dateLabel": "3月25–27日",
    "name": "SEMICON China 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★★☆☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Shanghai New International Expo Centre, Shanghai, China",
    "status": "不参加",
    "assignment": "—",
    "purpose": "中国半導体製造装置・材料・プロセス。不参加。"
  },
  {
    "id": "20260407-robosoft-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-04-07",
    "year": 2026,
    "dateLabel": "4月7–11日",
    "name": "RoboSoft 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★☆☆",
    "category": "Soft Robotics / Haptics",
    "type": "学会・専門会議",
    "location": "Kanazawa, Japan",
    "status": "参加済み",
    "assignment": "中島・高野",
    "purpose": "ソフトロボティクス、触覚、柔軟機構、接触作業。Soft Roboticsカテゴリの代表実績だが、AI×Robotics全体では補完領域。"
  },
  {
    "id": "20260413-modex-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-04-13",
    "year": 2026,
    "dateLabel": "4月13–16日",
    "name": "MODEX 2026",
    "budgetCandidate": true,
    "importance": "★★★☆☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Georgia World Congress Center, Atlanta, GA, United States",
    "status": "参加済み",
    "assignment": "北尾・山根",
    "purpose": "北米物流・マテハン・倉庫自動化"
  },
  {
    "id": "20260414-interclean-amsterdam-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-04-14",
    "year": 2026,
    "dateLabel": "4月14–17日",
    "name": "Interclean Amsterdam 2026",
    "budgetCandidate": true,
    "importance": "★★☆☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "RAI Amsterdam, Amsterdam, Netherlands",
    "status": "参加済み",
    "assignment": "仲西・下本・酒井・田原",
    "purpose": "業務用清掃、施設管理、清掃ロボット、衛生・メンテナンス"
  },
  {
    "id": "20260420-hannover-messe-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-04-20",
    "year": 2026,
    "dateLabel": "4月20–24日",
    "name": "Hannover Messe 2026",
    "budgetCandidate": true,
    "importance": "★★★☆☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Hannover Exhibition Grounds, Hannover, Germany",
    "status": "参加済み",
    "assignment": "谷阪・保木・田中大・田原・仲西",
    "purpose": "総合産業・FA・スマート製造"
  },
  {
    "id": "20260423-iclr-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-04-23",
    "year": 2026,
    "dateLabel": "4月23–27日",
    "name": "ICLR 2026",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★☆☆☆",
    "category": "Robot Learning / AI基盤",
    "type": "学会・専門会議",
    "location": "Riocentro Convention and Event Center, Rio de Janeiro, Brazil",
    "status": "論文・発表追跡",
    "assignment": "—",
    "purpose": "AI基盤・表現学習。現地参加せず、Robot Learning / Embodied AI関連の論文・Workshopを追跡"
  },
  {
    "id": "20260504-act-expo-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-05-04",
    "year": 2026,
    "dateLabel": "5月4–7日",
    "name": "ACT Expo 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★★☆☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Las Vegas Convention Center, Las Vegas, NV, United States",
    "status": "参加済み",
    "assignment": "仲西・谷川",
    "purpose": "EV、水素、Clean Fleet、充電・燃料インフラ、AI・自律システム"
  },
  {
    "id": "20260505-semicon-southeast-asia-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-05-05",
    "year": 2026,
    "dateLabel": "5月5–7日",
    "name": "SEMICON Southeast Asia 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "MITEC, Kuala Lumpur, Malaysia",
    "status": "参加済み",
    "assignment": "村上・大槻",
    "purpose": "東南アジアの半導体製造装置・材料・プロセス。参加内容を社内共有対象とする。"
  },
  {
    "id": "20260517-acsmo-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-05-17",
    "year": 2026,
    "dateLabel": "5月17–21日",
    "name": "ACSMO 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★☆",
    "category": "Mechanical Design / Structural & Multidisciplinary Optimization",
    "type": "学会・専門会議",
    "location": "Busan, Republic of Korea",
    "status": "参加済み",
    "assignment": "中島・松四",
    "purpose": "Busan。構造・形状・トポロジー・複合領域最適化。メカ設計最適化カテゴリの代表実績だが、AI×Robotics全体では補完領域。"
  },
  {
    "id": "20260526-acc-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-05-26",
    "year": 2026,
    "dateLabel": "5月26–29日",
    "name": "ACC 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★☆☆",
    "category": "Control / Motion / Systems",
    "type": "学会・専門会議",
    "location": "Hilton New Orleans Riverside, New Orleans, LA, United States",
    "status": "不参加",
    "assignment": "—",
    "purpose": "American Control Conference。IFAC World Congressを優先し、2026年は不参加"
  },
  {
    "id": "20260527-robotics-summit-and-expo-rse-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-05-27",
    "year": 2026,
    "dateLabel": "5月27–28日",
    "name": "Robotics Summit & Expo (RSE) 2026",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★★★☆",
    "category": "Robotics / Physical AI本体",
    "type": "技術カンファレンス・サミット",
    "location": "Boston Convention and Exhibition Center, Boston, MA, United States",
    "status": "参加済み",
    "assignment": "村上・佐藤・三浦",
    "purpose": "ロボット開発、商用化、実装・事業化動向 参加済み。"
  },
  {
    "id": "20260528-humanoids-summit-tokyo-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-05-28",
    "year": 2026,
    "dateLabel": "5月28–29日",
    "name": "Humanoids Summit Tokyo 2026",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★★★☆",
    "category": "Robotics / Physical AI本体",
    "type": "技術カンファレンス・サミット",
    "location": "Takanawa Gateway Convention Center, Tokyo, Japan",
    "status": "不参加",
    "assignment": "—",
    "purpose": "国内開催。ヒューマノイド、Embodied AI、商用化、量産、投資・事業化動向を確認する候補。不参加。"
  },
  {
    "id": "20260601-icra-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-06-01",
    "year": 2026,
    "dateLabel": "6月1–5日",
    "name": "ICRA 2026",
    "budgetCandidate": false,
    "importance": "★★★★★",
    "businessFit": "★★★★☆",
    "category": "Robotics / Physical AI本体",
    "type": "学会・専門会議",
    "location": "Vienna, Austria",
    "status": "参加済み",
    "assignment": "村上・佐藤・傳田・岡部",
    "purpose": "Physical AI / Robotics全体動向の主軸 参加済み。"
  },
  {
    "id": "20260603-cvpr-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-06-03",
    "year": 2026,
    "dateLabel": "6月3–7日",
    "name": "CVPR 2026",
    "budgetCandidate": false,
    "importance": "★★★★★",
    "businessFit": "★★★☆☆",
    "category": "Vision / 3D認識",
    "type": "学会・専門会議",
    "location": "Denver, Colorado, United States",
    "status": "参加済み",
    "assignment": "鉢木・田中昌",
    "purpose": "画像認識、3D認識、空間理解、視覚基盤モデル 参加済み。"
  },
  {
    "id": "20260608-london-tech-week-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-06-08",
    "year": 2026,
    "dateLabel": "6月8–12日",
    "name": "London Tech Week 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★☆☆☆",
    "category": "Technology Foresight / Innovation",
    "type": "技術カンファレンス・サミット",
    "location": "Olympia London, London, United Kingdom",
    "status": "不参加",
    "assignment": "—",
    "purpose": "欧州最大級の総合テックフェスティバル。来場者3万人超、エンタープライズAI・DXが主要テーマ。2026年は不参加。"
  },
  {
    "id": "20260615-awe-usa-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-06-15",
    "year": 2026,
    "dateLabel": "6月15–18日",
    "name": "AWE USA 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★☆☆☆",
    "category": "Technology Foresight / Innovation",
    "type": "技術カンファレンス・サミット",
    "location": "Long Beach Convention Center, Long Beach, CA, United States",
    "status": "不参加",
    "assignment": "—",
    "purpose": "XR、Spatial AI、AR/VR、ヒューマンインターフェース、空間コンピューティングの探索候補。不参加。"
  },
  {
    "id": "20260617-vivatech-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-06-17",
    "year": 2026,
    "dateLabel": "6月17–20日",
    "name": "VivaTech 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★☆☆☆",
    "category": "Technology Foresight / Innovation",
    "type": "技術カンファレンス・サミット",
    "location": "Paris Expo Porte de Versailles, Paris, France",
    "status": "参加済み",
    "assignment": "北尾",
    "purpose": "欧州スタートアップ・事業探索 参加済み。"
  },
  {
    "id": "20260622-automate-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-06-22",
    "year": 2026,
    "dateLabel": "6月22–25日",
    "name": "Automate 2026",
    "budgetCandidate": true,
    "importance": "★★★★★",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "McCormick Place, Chicago, IL, United States",
    "status": "参加済み",
    "assignment": "熊谷・橋本翔・田原",
    "purpose": "北米ロボット・自動化・マシンビジョン・モーション 参加済み。"
  },
  {
    "id": "20260628-robomech-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-06-28",
    "year": 2026,
    "dateLabel": "6月28日–7月1日",
    "name": "ROBOMECH 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★★☆☆",
    "category": "Robotics / Physical AI本体",
    "type": "学会・専門会議",
    "location": "福岡国際会議場, Fukuoka, Japan",
    "status": "不参加",
    "assignment": "—",
    "purpose": "国内ロボティクス・メカトロニクス研究、若手発表・育成候補。不参加。"
  },
  {
    "id": "20260706-icml-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-07-06",
    "year": 2026,
    "dateLabel": "7月6–11日",
    "name": "ICML 2026",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★☆☆☆",
    "category": "Robot Learning / AI基盤",
    "type": "学会・専門会議",
    "location": "Seoul, Republic of Korea",
    "status": "不参加",
    "assignment": "—",
    "purpose": "機械学習本流。ICRA / CVPR / CoRLを優先し、2026年は不参加。"
  },
  {
    "id": "20260707-aim-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-07-07",
    "year": 2026,
    "dateLabel": "7月7–11日",
    "name": "AIM 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★☆",
    "category": "Industrial Automation / Smart Factory",
    "type": "学会・専門会議",
    "location": "Genova, Italy",
    "status": "不参加",
    "assignment": "—",
    "purpose": "IEEE/ASME International Conference on Advanced Intelligent Mechatronics。2026年は不参加。"
  },
  {
    "id": "20260712-ifors-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-07-12",
    "year": 2026,
    "dateLabel": "7月12–17日",
    "name": "IFORS 2026",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★★★★",
    "category": "OR / Optimization / Decision Science",
    "type": "学会・専門会議",
    "location": "Vienna, Austria",
    "status": "参加済み",
    "assignment": "北村・熊谷",
    "purpose": "OR、最適化、物流、工程、スケジューリング。参加済み。"
  },
  {
    "id": "20260713-rss-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-07-13",
    "year": 2026,
    "dateLabel": "7月13–17日",
    "name": "RSS 2026",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★★☆☆",
    "category": "Robotics / Physical AI本体",
    "type": "学会・専門会議",
    "location": "Sydney, Australia",
    "status": "参加済み",
    "assignment": "村上",
    "purpose": "ロボティクス分野トップ会議。ICRA参加後の追加深掘り枠として、本会議・Keynote・Workshopを含めて参加済み。部門派遣ではなく、R&Dトップの単独探索枠。"
  },
  {
    "id": "20260719-isfa-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-07-19",
    "year": 2026,
    "dateLabel": "7月19–23日",
    "name": "ISFA 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★★★☆",
    "category": "Industrial Automation / Smart Factory",
    "type": "学会・専門会議",
    "location": "Okayama Convention Center, Okayama, Japan",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "Flexible Automation、製造システム、メカトロ、AI/IoT活用 参加判断対象ではなく、技術・市場動向の参考情報として扱う。"
  },
  {
    "id": "20260719-siggraph-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-07-19",
    "year": 2026,
    "dateLabel": "7月19–23日",
    "name": "SIGGRAPH 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★☆☆",
    "category": "Simulation / Digital Twin / CG",
    "type": "学会・専門会議",
    "location": "Los Angeles Convention Center, Los Angeles, CA, United States",
    "status": "参加済み",
    "assignment": "深川",
    "purpose": "CG、Simulation、3D表現。SIGGRAPH Asiaとの差分確認 参加済み。"
  },
  {
    "id": "20260815-ijcai-ecai-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-08-15",
    "year": 2026,
    "dateLabel": "8月15–21日",
    "name": "IJCAI-ECAI 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★☆☆☆☆",
    "category": "Robot Learning / AI基盤",
    "type": "学会・専門会議",
    "location": "Bremen, Germany",
    "status": "不参加",
    "assignment": "—",
    "purpose": "AI全般の総合会議。計画、推論、マルチエージェント、知識表現などは関連するが、ロボット実機、身体性AI、Sim2Real、ロボット学習が中心ではない。AI×Robotics調査ではCoRL / ICRA / CVPR / GTCを優先するため、2026年は不参加。"
  },
  {
    "id": "20260817-case-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-08-17",
    "year": 2026,
    "dateLabel": "8月17–21日",
    "name": "CASE 2026",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★★★★",
    "category": "Industrial Automation / Smart Factory",
    "type": "学会・専門会議",
    "location": "Shenyang, China",
    "status": "参加済み",
    "assignment": "北村",
    "purpose": "産業自動化、Smart Factory、製造・物流システム"
  },
  {
    "id": "20260819-world-robot-conference-and-expo-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-08-19",
    "year": 2026,
    "dateLabel": "8月19–23日",
    "name": "World Robot Conference and Expo 2026",
    "budgetCandidate": true,
    "importance": "★★★★☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Beijing, China",
    "status": "参加済み",
    "assignment": "保木・渡邊・古谷",
    "purpose": "中国ロボット産業、ヒューマノイド、政策・標準化・社会実装。2026年は保木・渡邊・古谷の3名が参加。"
  },
  {
    "id": "20260823-ifac-world-congress-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-08-23",
    "year": 2026,
    "dateLabel": "8月23–28日",
    "name": "IFAC World Congress 2026",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★★★★",
    "category": "Control / Motion / Systems",
    "type": "学会・専門会議",
    "location": "Busan, Republic of Korea",
    "status": "参加済み",
    "assignment": "角口・小西",
    "purpose": "制御・モーション・システム基盤。角口・小西が参加。"
  },
  {
    "id": "20260823-asme-idetc-cie-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-08-23",
    "year": 2026,
    "dateLabel": "8月23–26日",
    "name": "ASME IDETC/CIE 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★☆☆☆",
    "category": "Mechanical Design / Structural & Multidisciplinary Optimization",
    "type": "学会・専門会議",
    "location": "Hilton Americas-Houston, Houston, TX, United States",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "設計工学、Design Automation、CIE、メカ設計・最適化の参考情報"
  },
  {
    "id": "20260824-ro-man-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-08-24",
    "year": 2026,
    "dateLabel": "8月24–28日",
    "name": "RO-MAN 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★☆☆",
    "category": "HRI / Human Factors",
    "type": "学会・専門会議",
    "location": "Kitakyushu, Japan",
    "status": "参加済み",
    "assignment": "尾中",
    "purpose": "国内開催。HRI、人協働、受容性、ロボットコミュニケーションを調査。尾中が参加。"
  },
  {
    "id": "20260830-dynamics-and-design-conference-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-08-30",
    "year": 2026,
    "dateLabel": "8月30日–9月2日",
    "name": "Dynamics and Design Conference 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★★★☆",
    "category": "Control / Motion / Systems",
    "type": "学会・専門会議",
    "location": "長良川国際会議場, Gifu, Japan",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "機械力学、計測制御、振動・ダイナミクス、モーション基盤の国内参考情報"
  },
  {
    "id": "20260901-rsj-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-09-01",
    "year": 2026,
    "dateLabel": "9月1–4日",
    "name": "RSJ 2026（日本ロボット学会学術講演会）",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★☆☆",
    "category": "Robotics / Physical AI本体",
    "type": "学会・専門会議",
    "location": "Kanazawa University, Kanazawa, Japan",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "国内ロボティクス最大の学術講演会（第44回）。国内大学・企業の研究動向をまとめて確認できる。渡航を伴わない。",
    "sourceUrl": "https://ac.rsj-web.org/2026/",
    "verifiedAt": "2026-09-23"
  },
  {
    "id": "20260902-semicon-taiwan-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-09-02",
    "year": 2026,
    "dateLabel": "9月2–4日",
    "name": "SEMICON Taiwan 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "TaiNEX 1&2, Taipei, Taiwan",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "台湾半導体製造装置・材料・プロセス・先端パッケージング 参加判断対象ではなく、技術・市場動向の参考情報として扱う。"
  },
  {
    "id": "20260908-eccv-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-09-08",
    "year": 2026,
    "dateLabel": "9月8–12日",
    "name": "ECCV 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★☆☆☆",
    "category": "Vision / 3D認識",
    "type": "学会・専門会議",
    "location": "Malmö Arena and Malmömässan, Malmö, Sweden",
    "status": "論文・発表追跡",
    "assignment": "—",
    "purpose": "欧州Computer Vision本流。CVPR参加を前提に、ロボットビジョン・3D・空間理解を追跡"
  },
  {
    "id": "20260908-etfa-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-09-08",
    "year": 2026,
    "dateLabel": "9月8–11日",
    "name": "ETFA 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★☆",
    "category": "Industrial Automation / Smart Factory",
    "type": "学会・専門会議",
    "location": "Västerås Kongress, Västerås, Sweden",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "IEEE-IES主催（第31回）。工場自動化、産業通信、リアルタイム制御。Humanoid Robotics Summit Europe 2026と日程が重なる。",
    "sourceUrl": "https://etfa2026.ieee-ies.org/",
    "verifiedAt": "2026-09-23"
  },
  {
    "id": "20260909-humanoid-robotics-summit-europe-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-09-09",
    "year": 2026,
    "dateLabel": "9月9–11日",
    "name": "Humanoid Robotics Summit Europe 2026",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★★★☆",
    "category": "Robotics / Physical AI本体",
    "type": "技術カンファレンス・サミット",
    "location": "Stuttgart, Germany",
    "status": "参加済み",
    "assignment": "村上・古谷",
    "purpose": "欧州のヒューマノイド、Physical AI、産業実装・企業動向。村上・古谷が参加。"
  },
  {
    "id": "20260914-imts-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-09-14",
    "year": 2026,
    "dateLabel": "9月14–19日",
    "name": "IMTS 2026",
    "budgetCandidate": true,
    "importance": "★★★☆☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "McCormick Place, Chicago, IL, United States",
    "status": "参加済み",
    "assignment": "廣瀬",
    "purpose": "工作機械、製造技術、デジタル製造。廣瀬が参加。"
  },
  {
    "id": "20260915-amb-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-09-15",
    "year": 2026,
    "dateLabel": "9月15–19日",
    "name": "AMB 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Messe Stuttgart, Stuttgart, Germany",
    "status": "参加済み",
    "assignment": "廣瀬・池崎",
    "purpose": "金属加工、工作機械、生産技術。廣瀬・池崎が参加。"
  },
  {
    "id": "20260922-roscon-global-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-09-22",
    "year": 2026,
    "dateLabel": "9月22–24日",
    "name": "ROSCon Global 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★☆",
    "category": "Embedded / Edge / Real-time Systems",
    "type": "技術カンファレンス・サミット",
    "location": "Toronto, Canada",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "ROS開発者カンファレンス。ロボット実装基盤・OSS・開発者コミュニティの参考情報"
  },
  {
    "id": "20260927-iros-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-09-27",
    "year": 2026,
    "dateLabel": "9月27日–10月1日",
    "name": "IROS 2026",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★★★☆",
    "category": "Robotics / Physical AI本体",
    "type": "学会・専門会議",
    "location": "Pittsburgh, Pennsylvania, United States",
    "status": "参加予定",
    "assignment": "酒井・羽山",
    "purpose": "知能ロボット・ロボットシステムの分野トップ会議。酒井・羽山が参加し、内容をR&D内で共有する予定。"
  },
  {
    "id": "20261004-smc-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-10-04",
    "year": 2026,
    "dateLabel": "10月4–7日",
    "name": "SMC 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★☆☆",
    "category": "HRI / Human Factors",
    "type": "学会・専門会議",
    "location": "Bellevue, WA, United States",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "IEEE International Conference on Systems, Man, and Cybernetics。人間機械系、システム、サイバネティクスの参考情報"
  },
  {
    "id": "20261005-world-summit-ai-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-10-05",
    "year": 2026,
    "dateLabel": "10月5–9日",
    "name": "World Summit AI 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★☆☆☆☆",
    "category": "Technology Foresight / Innovation",
    "type": "技術カンファレンス・サミット",
    "location": "Amsterdam, Netherlands",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "AI企業・政策・スタートアップ・社会実装トレンドの探索参考情報"
  },
  {
    "id": "20261006-vision-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-10-06",
    "year": 2026,
    "dateLabel": "10月6–8日",
    "name": "VISION 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★☆",
    "category": "Vision / 3D認識",
    "type": "展示会・見本市",
    "location": "Messe Stuttgart, Stuttgart, Germany",
    "status": "参加予定",
    "assignment": "橋本将",
    "purpose": "マシンビジョン、画像処理、産業用カメラ・検査の展示会参加予定。部門予算化候補には含めない。"
  },
  {
    "id": "20261012-ciif-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-10-12",
    "year": 2026,
    "dateLabel": "10月12–16日",
    "name": "CIIF 2026（中国国際工業博覧会）",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "National Exhibition and Convention Center, Shanghai, China",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "中国最大級の総合工業展（第26回）。ロボット専門館を併設。中国の産業自動化・ロボット実装動向。",
    "sourceUrl": "https://www.ciif-expo.com/",
    "verifiedAt": "2026-09-23"
  },
  {
    "id": "20261013-semicon-west-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-10-13",
    "year": 2026,
    "dateLabel": "10月13–15日",
    "name": "SEMICON West 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Moscone Center, San Francisco, CA, United States",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "北米半導体製造装置・材料・プロセス・先端パッケージング 参加判断対象ではなく、技術・市場動向の参考情報として扱う。"
  },
  {
    "id": "20261018-iecon-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-10-18",
    "year": 2026,
    "dateLabel": "10月18–21日",
    "name": "IECON 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★★☆☆",
    "category": "Industrial Automation / Smart Factory",
    "type": "学会・専門会議",
    "location": "Doha, Qatar",
    "status": "不参加",
    "assignment": "—",
    "purpose": "Industrial Electronics全般。2026年は不参加。"
  },
  {
    "id": "20261019-techex-europe-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-10-19",
    "year": 2026,
    "dateLabel": "10月19–20日",
    "name": "TechEx Europe 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★☆☆☆",
    "category": "Technology Foresight / Innovation",
    "type": "技術カンファレンス・サミット",
    "location": "RAI Amsterdam, Amsterdam, Netherlands",
    "status": "参加予定",
    "assignment": "村上",
    "purpose": "IoT、AI、Edge、デジタル基盤",
    "sourceUrl": "https://techexevent.com/europe/",
    "verifiedAt": "2026-09-19"
  },
  {
    "id": "20261020-euroblech-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-10-20",
    "year": 2026,
    "dateLabel": "10月20–23日",
    "name": "EuroBLECH 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Hannover Exhibition Grounds, Hannover, Germany",
    "status": "参加予定",
    "assignment": "村上・金築・美馬",
    "purpose": "板金加工、レーザ、成形、加工自動化。参加予定。"
  },
  {
    "id": "20261025-mecc-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-10-25",
    "year": 2026,
    "dateLabel": "10月25–28日",
    "name": "MECC 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★☆☆",
    "category": "Control / Motion / Systems",
    "type": "学会・専門会議",
    "location": "Phoenix, AZ, United States",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "Modeling, Estimation and Control。動的システムのモデリング・推定・制御参考情報"
  },
  {
    "id": "20261026-jimtof-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-10-26",
    "year": 2026,
    "dateLabel": "10月26–31日",
    "name": "JIMTOF 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Tokyo Big Sight, Tokyo, Japan",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "工作機械、加工、計測、製造技術の国内大型展示会参考情報"
  },
  {
    "id": "20261101-informs-annual-meeting-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-11-01",
    "year": 2026,
    "dateLabel": "11月1–4日",
    "name": "INFORMS Annual Meeting 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★★☆☆",
    "category": "OR / Optimization / Decision Science",
    "type": "学会・専門会議",
    "location": "San Francisco, CA, United States",
    "status": "不参加",
    "assignment": "—",
    "purpose": "OR/MS/Analytics。IFORS後に必要性判断"
  },
  {
    "id": "20261103-cemat-asia-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-11-03",
    "year": 2026,
    "dateLabel": "11月3–6日",
    "name": "CeMAT ASIA 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Shanghai New International Expo Centre, Shanghai, China",
    "status": "不参加",
    "assignment": "—",
    "purpose": "中国・アジアの物流・倉庫自動化市場"
  },
  {
    "id": "20261109-corl-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-11-09",
    "year": 2026,
    "dateLabel": "11月9–12日",
    "name": "CoRL 2026",
    "budgetCandidate": false,
    "importance": "★★★★★",
    "businessFit": "★★★☆☆",
    "category": "Robot Learning / AI基盤",
    "type": "学会・専門会議",
    "location": "Austin, Texas, United States",
    "status": "参加予定",
    "assignment": "熊谷・佐藤元",
    "purpose": "Robot Learning、VLA、Sim2Real、基盤モデル"
  },
  {
    "id": "20261110-semicon-europa-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-11-10",
    "year": 2026,
    "dateLabel": "11月10–13日",
    "name": "SEMICON Europa 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Trade Fair Center Messe München, Munich, Germany",
    "status": "参加予定",
    "assignment": "寺田・三枝",
    "purpose": "欧州半導体製造装置・材料・プロセス。electronica 2026と同日程・同会場で併催。electronicaに参加する寺田・三枝が合わせて参加予定。"
  },
  {
    "id": "20261110-electronica-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-11-10",
    "year": 2026,
    "dateLabel": "11月10–13日",
    "name": "electronica 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Trade Fair Center Messe München, Munich, Germany",
    "status": "参加予定",
    "assignment": "寺田・三枝",
    "purpose": "半導体、パッシブ部品、組込みシステム、パワーエレクトロニクス等、電子部品・技術全般を扱う世界最大級の電子部品展示会。SEMICON Europa 2026と同日程・同会場で併催。寺田・三枝が参加予定。"
  },
  {
    "id": "20261116-isrr-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-11-16",
    "year": 2026,
    "dateLabel": "11月16–20日",
    "name": "ISRR 2026",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★★☆☆",
    "category": "Robotics / Physical AI本体",
    "type": "学会・専門会議",
    "location": "Casa del Rio Melaka Hotel, Malacca, Malaysia",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "IFRR主催の招待制シンポジウム。ロボティクス研究の方向性を少人数で議論する場。ITMA ASIA + CITME 2026の直前。",
    "sourceUrl": "https://isrr2026.su.domains/",
    "verifiedAt": "2026-09-23"
  },
  {
    "id": "20261117-formnext-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-11-17",
    "year": 2026,
    "dateLabel": "11月17–20日",
    "name": "Formnext 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Frankfurt Fair & Exhibition Centre, Frankfurt am Main, Germany",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "アディティブマニュファクチャリング、工業用3Dプリンティング、次世代製造技術の参考情報。"
  },
  {
    "id": "20261120-itma-asia-citme-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-11-20",
    "year": 2026,
    "dateLabel": "11月20–24日",
    "name": "ITMA ASIA + CITME 2026",
    "budgetCandidate": true,
    "importance": "★★☆☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "National Exhibition and Convention Center, Shanghai, China",
    "status": "不参加",
    "assignment": "—",
    "purpose": "繊維機械・繊維製造技術"
  },
  {
    "id": "20261124-sps-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-11-24",
    "year": 2026,
    "dateLabel": "11月24–26日",
    "name": "SPS 2026",
    "budgetCandidate": true,
    "importance": "★★★☆☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Nuremberg, Germany",
    "status": "参加予定",
    "assignment": "東",
    "purpose": "Smart Production Solutions。FA、産業制御、産業通信、ドライブ、センサ等を確認する。東が参加予定。"
  },
  {
    "id": "20261201-siggraph-asia-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-12-01",
    "year": 2026,
    "dateLabel": "12月1–4日",
    "name": "SIGGRAPH Asia 2026",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★★★☆",
    "category": "Simulation / Digital Twin / CG",
    "type": "学会・専門会議",
    "location": "KLCC, Kuala Lumpur, Malaysia",
    "status": "候補",
    "assignment": "TBD",
    "purpose": "Digital Twin、Simulation、3D表現、生成表現"
  },
  {
    "id": "20261202-robonext-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-12-02",
    "year": 2026,
    "dateLabel": "12月2–4日",
    "name": "RoboNext 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "INTEX Osaka, Osaka, Japan",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "日本ロボット工業会・日刊工業新聞社主催。iREXの中間年に2026年から新設された展示会。ロボット導入が進んでいない分野への適用提案が主題。渡航を伴わない。",
    "sourceUrl": "https://robonext.nikkan.co.jp/",
    "verifiedAt": "2026-09-23"
  },
  {
    "id": "20261203-ros-industrial-conference-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-12-03",
    "year": 2026,
    "dateLabel": "12月3–4日",
    "name": "ROS-Industrial Conference 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★☆",
    "category": "Embedded / Edge / Real-time Systems",
    "type": "技術カンファレンス・サミット",
    "location": "Fraunhofer IPA, Stuttgart, Germany",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "ROS-Industrial。産業ロボット実装、OSS、システムインテグレーションの参考情報"
  },
  {
    "id": "20261206-humanoids-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-12-06",
    "year": 2026,
    "dateLabel": "12月6–9日",
    "name": "Humanoids 2026",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★★☆☆",
    "category": "Robotics / Physical AI本体",
    "type": "学会・専門会議",
    "location": "Santa Clara, California, United States",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "ヒューマノイド、全身制御、身体性AIの主要専門会議。AI×Robotics / Physical AI観点では重要だが、2026年の参加者はTBD。 参加判断対象ではなく、技術・市場動向の参考情報として扱う。"
  },
  {
    "id": "20261206-neurips-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-12-06",
    "year": 2026,
    "dateLabel": "12月6–12日",
    "name": "NeurIPS 2026",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★☆☆☆",
    "category": "Robot Learning / AI基盤",
    "type": "学会・専門会議",
    "location": "Sydney / Atlanta / Paris",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "AI基盤のトップ会議。現地参加せず、Embodied AI / World Model / Robotics関連Workshopと論文を追跡 参加判断対象ではなく、技術・市場動向の参考情報として扱う。"
  },
  {
    "id": "20261207-gitex-global-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-12-07",
    "year": 2026,
    "dateLabel": "12月7–11日",
    "name": "GITEX Global 2026",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★☆☆☆",
    "category": "Technology Foresight / Innovation",
    "type": "技術カンファレンス・サミット",
    "location": "Dubai Exhibition Centre, Expo City Dubai, UAE",
    "status": "候補",
    "assignment": "TBD",
    "purpose": "AI、デジタル、スタートアップ、市場探索"
  },
  {
    "id": "20261209-semicon-japan-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-12-09",
    "year": 2026,
    "dateLabel": "12月9–11日",
    "name": "SEMICON Japan 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Tokyo Big Sight, Tokyo, Japan",
    "status": "候補",
    "assignment": "TBD",
    "purpose": "国内半導体製造装置・材料・先端パッケージング・検査計測"
  },
  {
    "id": "20261215-cdc-2026",
    "dateStatus": "confirmed",
    "sortDate": "2026-12-15",
    "year": 2026,
    "dateLabel": "12月15–18日",
    "name": "CDC 2026",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★☆☆",
    "category": "Control / Motion / Systems",
    "type": "学会・専門会議",
    "location": "Hilton Hawaiian Village, Honolulu, HI, United States",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "IEEE Conference on Decision and Control。制御理論・意思決定・最適制御。2026年は不参加 参加判断対象ではなく、技術・市場動向の参考情報として扱う。"
  },
  {
    "id": "20270106-ces-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-01-06",
    "year": 2027,
    "dateLabel": "1月6–9日",
    "name": "CES 2027",
    "budgetCandidate": true,
    "importance": "★★☆☆☆",
    "businessFit": "★★☆☆☆",
    "category": "Technology Foresight / Innovation",
    "type": "技術カンファレンス・サミット",
    "location": "Las Vegas, Nevada, United States",
    "status": "2027計画",
    "assignment": "田原・公募2名",
    "purpose": "広域技術・事業探索"
  },
  {
    "id": "20270120-advanced-humanoid-forum-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-01-20",
    "year": 2027,
    "dateLabel": "1月20–21日",
    "name": "Advanced Humanoid Forum 2027（旧 Humanoid Evolution Summit）",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★☆☆",
    "category": "Robotics / Physical AI本体",
    "type": "技術カンファレンス・サミット",
    "location": "Midnightbazar Munich, Munich, Germany",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "欧州のヒューマノイド、Physical AI、Digital Twin、産業実装・事業化動向を部門で把握する参考情報。2027年が初開催のため、参加はプログラム・登壇企業・展示内容の具体化後に判断する。 主催はULMO-Consulting（Ulrich Möller）。旧名Humanoid Evolution Summitの公式ドメインはこのサイトへ転送される。定員500名で、産業導入・実機検証（Physical AI validation）を前面に出す。",
    "sourceUrl": "https://www.advancedhumanoidforum.com/",
    "verifiedAt": "2026-09-23"
  },
  {
    "id": "20270203-physical-ai-expo-global-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-02-03",
    "year": 2027,
    "dateLabel": "2月3–4日",
    "name": "Physical AI Expo Global 2027（TechEx Global）",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★☆☆",
    "category": "Robotics / Physical AI本体",
    "type": "技術カンファレンス・サミット",
    "location": "Olympia London, London, United Kingdom",
    "status": "候補",
    "assignment": "TBD",
    "purpose": "TechEx Events Ltd主催。TechEx Globalの8つの併催イベントの1つで、Physical AI単独の開催ではない。企業導入・周辺IT寄り。North America版（6月）と同じシリーズなので、両方を別々の派遣候補として積み上げず、地域・時期で選ぶ。11VC主催の「THE Physical AI Expo」とは別イベント。",
    "sourceUrl": "https://physicalaiconference.com/global/",
    "verifiedAt": "2026-09-23"
  },
  {
    "id": "20270209-md-and-m-west-2027-automation-sector-atx-west",
    "dateStatus": "confirmed",
    "sortDate": "2027-02-09",
    "year": 2027,
    "dateLabel": "2月9–11日",
    "name": "MD&M West 2027（Automation Sector／旧ATX West）",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★★☆☆",
    "category": "Industrial Automation / Smart Factory",
    "type": "展示会・見本市",
    "location": "Anaheim Convention Center, Anaheim, CA, United States",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "Automation、ロボティクス、センサ、Motion Control、製造技術を扱うMD&M West内の展示分野。Automate、ProMat等との重複を踏まえ、北米西海岸の製造・MedTech・包装分野を含む市場動向の参考情報として管理する。"
  },
  {
    "id": "20270211-is-pair-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-02-11",
    "year": 2027,
    "dateLabel": "2月11–12日",
    "name": "IS-PAIR 2027",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★☆☆☆",
    "category": "Robotics / Physical AI本体",
    "type": "学会・専門会議",
    "location": "VISTEC, Rayong, Thailand",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "第3回International Symposium on Physical Artificial Intelligence and Robotics。VISTEC・東北大学・国立情報学研究所の共同主催。生物知能から身体知能への学際テーマ。Tier1外の小規模会議のため、共同研究や特定テーマがある場合に限って現地参加を考える。",
    "sourceUrl": "https://is-pair.vistec.ac.th/2027/",
    "verifiedAt": "2026-09-23"
  },
  {
    "id": "20270217-semicon-korea-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-02-17",
    "year": 2027,
    "dateLabel": "2月17–19日",
    "name": "SEMICON Korea 2027",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★★☆☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "COEXほか, Seoul, Republic of Korea",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "半導体装置・材料・プロセス。COEX全館に加え、Westin Seoul ParnasとGrand InterContinental Seoul Parnasで開催。",
    "sourceUrl": "https://www.semiconkorea.org/",
    "verifiedAt": "2026-09-16"
  },
  {
    "id": "20270301-mwc-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-03-01",
    "year": 2027,
    "dateLabel": "3月1–4日",
    "name": "MWC 2027",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★☆☆☆",
    "category": "Technology Foresight / Innovation",
    "type": "技術カンファレンス・サミット",
    "location": "Fira Barcelona Gran Via, Barcelona, Spain",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "通信・エッジ・AI/IoT基盤。部門の参加・予算計画には含めず、関連する市場・技術動向の参考情報として管理する。"
  },
  {
    "id": "20270302-jec-world-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-03-02",
    "year": 2027,
    "dateLabel": "3月2–4日",
    "name": "JEC World 2027",
    "budgetCandidate": true,
    "importance": "★★☆☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Paris Nord Villepinte, France",
    "status": "2027計画",
    "assignment": "TBD",
    "purpose": "複合材料"
  },
  {
    "id": "20270302-erf-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-03-02",
    "year": 2027,
    "dateLabel": "3月2–4日",
    "name": "European Robotics Forum 2027 (ERF)",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★★☆☆",
    "category": "Robotics / Physical AI本体",
    "type": "技術カンファレンス・サミット",
    "location": "Birmingham, United Kingdom",
    "status": "候補",
    "assignment": "TBD",
    "purpose": "euRoboticsの年次フォーラム（1,000名超）。欧州の研究・産業・政策の接点を見る場で、学会ほど研究発表寄りでも、展示会ほど展示寄りでもない。会期にはサイドイベントを含む。",
    "sourceUrl": "https://erf2027.eu/",
    "verifiedAt": "2026-09-23"
  },
  {
    "id": "20270314-gtc-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-03-14",
    "year": 2027,
    "dateLabel": "3月14–18日",
    "name": "GTC 2027",
    "budgetCandidate": true,
    "importance": "★★★★★",
    "businessFit": "★★★★☆",
    "category": "Technology Foresight / Innovation",
    "type": "技術カンファレンス・サミット",
    "location": "San Jose McEnery Convention Center and venues throughout San Jose, CA, United States",
    "status": "2027計画",
    "assignment": "1名",
    "purpose": "Physical AI、AI/GPU、ロボティクス基盤、Omniverse、シミュレーション、Edge AIの最重要候補。NVIDIA公式FAQでは全日程を3月14–18日、公式トップ／イベント一覧では本会議を3月15–18日と案内。",
    "dateNote": "本会議：15–18日"
  },
  {
    "id": "20270316-logimat-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-03-16",
    "year": 2027,
    "dateLabel": "3月16–18日",
    "name": "LogiMAT 2027",
    "budgetCandidate": true,
    "importance": "★★★☆☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Messe Stuttgart, Stuttgart, Germany",
    "status": "2027計画",
    "assignment": "～2名",
    "purpose": "物流・倉庫自動化"
  },
  {
    "id": "20270316-embedded-world-germany-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-03-16",
    "year": 2027,
    "dateLabel": "3月16–18日",
    "name": "embedded world Germany 2027",
    "budgetCandidate": true,
    "importance": "★★★☆☆",
    "businessFit": "★★★★☆",
    "category": "Embedded / Edge / Real-time Systems",
    "type": "展示会・見本市",
    "location": "Exhibition Centre Nuremberg, Nuremberg, Germany",
    "status": "2027計画",
    "assignment": "TBD",
    "purpose": "組込み、Edge AI、リアルタイム、機能安全、Embedded Vision。部門予算化計画。GTC 2027およびLogiMAT 2027と日程が重なるため別担当を前提に検討する。"
  },
  {
    "id": "20270330-semicon-west-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-03-30",
    "year": 2027,
    "dateLabel": "3月30日–4月1日",
    "name": "SEMICON West 2027",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Phoenix Convention Center, Phoenix, AZ, United States",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "北米半導体装置・材料・プロセス。2027年から春開催へ移行し、Phoenixを長期開催地とする。",
    "sourceUrl": "https://semiconwest.org/news-press/press-releases",
    "verifiedAt": "2026-09-16"
  },
  {
    "id": "20270405-hannover-messe-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-04-05",
    "year": 2027,
    "dateLabel": "4月5–8日",
    "name": "Hannover Messe 2027",
    "budgetCandidate": true,
    "importance": "★★★☆☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Hannover Exhibition Grounds, Hannover, Germany",
    "status": "2027計画",
    "assignment": "～2名",
    "purpose": "総合産業・FA"
  },
  {
    "id": "20270413-geia-asia-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-04-13",
    "year": 2027,
    "dateLabel": "4月13–16日",
    "name": "GEIA Asia 2027",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★★☆☆",
    "category": "Robotics / Physical AI本体",
    "type": "技術カンファレンス・サミット",
    "location": "Shanghai, China（都市未確認）",
    "status": "候補",
    "assignment": "TBD",
    "purpose": "Global Embodied Intelligence and Humanoid Innovation Asia。Embodied IntelligenceとHumanoidに絞った中国勢中心の会議で、会期後にSite Visitがある。日程は公式アジェンダで確認したが、都市と主催法人は公式ページで確認できていない。GEIA Europeと同じシリーズなので、どちらか一方を選ぶ。",
    "sourceUrl": "http://www.geiaasia.com/2027_GEIA_Asia_Agenda.html",
    "verifiedAt": "2026-09-23"
  },
  {
    "id": "20270419-promat-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-04-19",
    "year": 2027,
    "dateLabel": "4月19–21日",
    "name": "ProMat 2027",
    "budgetCandidate": true,
    "importance": "★★★★☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "McCormick Place, Chicago, IL, United States",
    "status": "2027計画",
    "assignment": "～2名",
    "purpose": "物流・マテハン・サプライチェーン"
  },
  {
    "id": "20270421-physical-ai-expo-nextech-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-04-21",
    "year": 2027,
    "dateLabel": "4月21–23日",
    "name": "フィジカルAI EXPO（NexTech Week 2027 春）",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Tokyo Big Sight, Tokyo, Japan",
    "status": "候補",
    "assignment": "TBD",
    "purpose": "RX Japan主催、NexTech Week春の6構成展の1つ。国内企業のPhysical AI導入動向を低コストで確認でき、海外イベントを選ぶ前の比較基準になる。渡航を伴わない。",
    "sourceUrl": "https://www.nextech-week.jp/spring/ja-jp.html",
    "verifiedAt": "2026-09-23"
  },
  {
    "id": "20270426-iclr-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-04-26",
    "year": 2027,
    "dateLabel": "4月26–30日",
    "name": "ICLR 2027",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★☆☆☆",
    "category": "Robot Learning / AI基盤",
    "type": "学会・専門会議",
    "location": "San Francisco, CA, United States",
    "status": "論文・発表追跡",
    "assignment": "—",
    "purpose": "AI基盤・表現学習。都市は公式のワークショップ募集ページ（4月29–30日、San Francisco）による。本会議の会場は未発表。",
    "sourceUrl": "https://iclr.cc/Conferences/2027",
    "verifiedAt": "2026-09-23"
  },
  {
    "id": "20270503-aamas-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-05-03",
    "year": 2027,
    "dateLabel": "5月3–7日",
    "name": "AAMAS 2027",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★☆☆☆",
    "category": "Robot Learning / AI基盤",
    "type": "学会・専門会議",
    "location": "JW Marriott Hanoi, Hanoi, Vietnam",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "自律エージェント・マルチエージェント系（第26回）。協調制御、分散意思決定。",
    "sourceUrl": "https://warwick.ac.uk/fac/sci/dcs/aamas2027/",
    "verifiedAt": "2026-09-23"
  },
  {
    "id": "20270510-automate-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-05-10",
    "year": 2027,
    "dateLabel": "5月10–13日",
    "name": "Automate 2027",
    "budgetCandidate": true,
    "importance": "★★★★★",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Las Vegas Convention Center, Las Vegas, NV, United States",
    "status": "2027計画",
    "assignment": "2名",
    "purpose": "北米最大級のロボット・自動化展示会。2027年はLas Vegas開催。部門予算化候補。"
  },
  {
    "id": "20270524-icra-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-05-24",
    "year": 2027,
    "dateLabel": "5月24–28日",
    "name": "ICRA 2027",
    "budgetCandidate": false,
    "importance": "★★★★★",
    "businessFit": "★★★★☆",
    "category": "Robotics / Physical AI本体",
    "type": "学会・専門会議",
    "location": "COEX, Seoul, Republic of Korea",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "Robotics代表会議。部門の参加・予算計画には含めず、論文・発表と個別参加判断の参考情報として管理する。"
  },
  {
    "id": "20270525-semicon-southeast-asia-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-05-25",
    "year": 2027,
    "dateLabel": "5月25–27日",
    "name": "SEMICON Southeast Asia 2027",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "MITEC, Kuala Lumpur, Malaysia",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "東南アジア半導体装置・材料・プロセス。Malaysia International Trade and Exhibition Centreで開催。",
    "sourceUrl": "https://www.semiconsea.org/Event-Overview",
    "verifiedAt": "2026-09-16"
  },
  {
    "id": "20270602-robotics-summit-and-expo-rse-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-06-02",
    "year": 2027,
    "dateLabel": "6月2–3日",
    "name": "Robotics Summit & Expo (RSE) 2027",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★★★☆",
    "category": "Robotics / Physical AI本体",
    "type": "技術カンファレンス・サミット",
    "location": "Boston, MA, United States",
    "status": "2027計画",
    "assignment": "1名",
    "purpose": "商用ロボット開発・実装寄りの技術カンファレンス／Expo。2027年6月2–3日、Boston開催を公式サイトで確認済み。"
  },
  {
    "id": "20270602-davos-tech-summit-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-06-02",
    "year": 2027,
    "dateLabel": "6月2–5日",
    "name": "Davos Tech Summit 2027",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★★☆☆",
    "category": "Robotics / Physical AI本体",
    "type": "技術カンファレンス・サミット",
    "location": "Davos, Switzerland",
    "status": "候補",
    "assignment": "TBD",
    "purpose": "Davos Congress主催。Robotics・Physical AI・実環境導入のカンファレンスに、展示とRobot City（実環境デモ）を組み合わせる。最終日の土曜は一般向けFamily Day。Robotics Summit & Expo（6/2–3、Boston）と会期が重なる。",
    "sourceUrl": "https://davostechsummit.com/",
    "verifiedAt": "2026-09-23"
  },
  {
    "id": "20270607-london-tech-week-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-06-07",
    "year": 2027,
    "dateLabel": "6月7–11日",
    "name": "London Tech Week 2027",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★☆☆☆",
    "category": "Technology Foresight / Innovation",
    "type": "技術カンファレンス・サミット",
    "location": "Olympia London, London, United Kingdom",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "欧州最大級の総合テックフェスティバル。エンタープライズAI・DX・スタートアップ動向の探索候補として参考情報で管理。"
  },
  {
    "id": "20270616-l4dc-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-06-16",
    "year": 2027,
    "dateLabel": "6月16–18日",
    "name": "L4DC 2027",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★★☆☆",
    "category": "Control / Motion / Systems",
    "type": "学会・専門会議",
    "location": "Stockholm, Sweden",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "学習と動力学・制御の接点を扱う会議（第9回）。KTH主催。会場名は未発表。",
    "sourceUrl": "https://l4dc2027.control.ee.ethz.ch/",
    "verifiedAt": "2026-09-23"
  },
  {
    "id": "20270616-physical-ai-expo-north-america-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-06-16",
    "year": 2027,
    "dateLabel": "6月16–17日",
    "name": "Physical AI Expo North America 2027（TechEx）",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★☆☆",
    "category": "Robotics / Physical AI本体",
    "type": "技術カンファレンス・サミット",
    "location": "San Jose McEnery Convention Center, San Jose, CA, United States",
    "status": "候補",
    "assignment": "TBD",
    "purpose": "TechEx Events Ltd主催。TechEx North Americaの併催イベントの1つ（全体で8,000名超・出展250超と公表）。Global版（2月、London）と同じシリーズなので、どちらか一方を選ぶ。",
    "sourceUrl": "https://physicalaiconference.com/northamerica/",
    "verifiedAt": "2026-09-23"
  },
  {
    "id": "20270620-cvpr-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-06-20",
    "year": 2027,
    "dateLabel": "6月20–25日",
    "name": "CVPR 2027",
    "budgetCandidate": false,
    "importance": "★★★★★",
    "businessFit": "★★★☆☆",
    "category": "Vision / 3D認識",
    "type": "学会・専門会議",
    "location": "Seattle, Washington, United States",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "画像認識、3D認識、空間理解、視覚基盤モデル。専用公式サイトは6月20–25日、CVF公式一覧は6月20–24日と案内が分かれるため、専用サイトの期間を採用。",
    "sourceUrl": "https://cvpr.thecvf.com/",
    "verifiedAt": "2026-09-16"
  },
  {
    "id": "20270621-ai-for-good-global-summit-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-06-21",
    "year": 2027,
    "dateLabel": "6月21–24日",
    "name": "AI for Good Global Summit 2027",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★☆☆☆☆",
    "category": "Technology Foresight / Innovation",
    "type": "技術カンファレンス・サミット",
    "location": "Palexpo, Geneva, Switzerland",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "ITU主催、50超の国連機関と連携し、スイス政府と共催。Physical AI専業ではなく、標準・政策・社会実装の情報源として追う。公式ページは見出しが6月21–24日、FAQが「21–25日の週」で揺れている。automatica（6/22–25）と会期が重なる。",
    "sourceUrl": "https://aiforgood.itu.int/summit27/",
    "verifiedAt": "2026-09-23"
  },
  {
    "id": "20270622-automatica-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-06-22",
    "year": 2027,
    "dateLabel": "6月22–25日",
    "name": "automatica 2027",
    "budgetCandidate": true,
    "importance": "★★★★☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Messe München, Munich, Germany",
    "status": "2027計画",
    "assignment": "1名",
    "purpose": "スマートオートメーション・ロボティクス"
  },
  {
    "id": "20270627-icaps-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-06-27",
    "year": 2027,
    "dateLabel": "6月27日–7月2日",
    "name": "ICAPS 2027",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★☆☆",
    "category": "Robot Learning / AI基盤",
    "type": "学会・専門会議",
    "location": "Columbia, SC, United States",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "プランニング・スケジューリング（第37回）。ロボットの行動計画とタスク割当。",
    "sourceUrl": "https://icaps27.icaps-conference.org/",
    "verifiedAt": "2026-09-23"
  },
  {
    "id": "20270706-rss-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-07-06",
    "year": 2027,
    "dateLabel": "7月6–11日",
    "name": "RSS 2027",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★★☆☆",
    "category": "Robotics / Physical AI本体",
    "type": "学会・専門会議",
    "location": "Athens, Greece",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "ロボティクス分野トップ会議。2027年7月6–11日、Athens開催。部門の参加・予算計画には含めず、論文・発表と個別参加判断の参考情報として管理する。"
  },
  {
    "id": "20270707-acc-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-07-07",
    "year": 2027,
    "dateLabel": "7月7–9日",
    "name": "ACC 2027",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★☆☆",
    "category": "Control / Motion / Systems",
    "type": "学会・専門会議",
    "location": "Philadelphia Marriott Downtown, Philadelphia, PA, United States",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "American Control Conference。制御理論の二大会議の一つ。前日7月6日にプレカンファレンス・ワークショップ。",
    "sourceUrl": "https://acc2027.a2c2.org/",
    "verifiedAt": "2026-09-23"
  },
  {
    "id": "20270712-world-haptics-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-07-12",
    "year": 2027,
    "dateLabel": "7月12–15日",
    "name": "World Haptics 2027",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★★☆☆",
    "category": "Soft Robotics / Haptics",
    "type": "学会・専門会議",
    "location": "Hilton Boston Park Plaza, Boston, MA, United States",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "触覚・力覚提示の最上位会議。IEEE Haptics Symposium（偶数年）と交互開催。接触作業と力制御の基盤。",
    "sourceUrl": "https://2027.worldhaptics.org/",
    "verifiedAt": "2026-09-23"
  },
  {
    "id": "20270808-siggraph-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-08-08",
    "year": 2027,
    "dateLabel": "8月8–12日",
    "name": "SIGGRAPH 2027",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★☆☆",
    "category": "Simulation / Digital Twin / CG",
    "type": "学会・専門会議",
    "location": "Anaheim, California, United States",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "Computer Graphics、Simulation、Digital Twin、3D表現、生成表現、XR。部門予算化はせず、Physical AIのシミュレーション・デジタル環境側を把握する参考情報として管理する。"
  },
  {
    "id": "20270910-ireai-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-09-10",
    "year": 2027,
    "dateLabel": "9月10–12日",
    "name": "IREAI 2027",
    "budgetCandidate": false,
    "importance": "★☆☆☆☆",
    "businessFit": "★☆☆☆☆",
    "category": "Robot Learning / AI基盤",
    "type": "学会・専門会議",
    "location": "China（都市未確認）",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "Intelligent Robot・Embodied AIがテーマ。公式サイトには事務局の連絡先しかなく、主催する大学・学会・法人も都市も確認できない。3日目はExcursion。主催者が明らかになるまで現地参加の候補にしない。",
    "sourceUrl": "https://www.ireai.org/",
    "verifiedAt": "2026-09-23"
  },
  {
    "id": "20270916-itma-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-09-16",
    "year": 2027,
    "dateLabel": "9月16–22日",
    "name": "ITMA 2027",
    "budgetCandidate": true,
    "importance": "★★☆☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Hannover Exhibition Grounds, Hannover, Germany",
    "status": "2027計画",
    "assignment": "前半：～2名／後半：～2名",
    "purpose": "繊維機械・繊維製造。会期前半・後半で担当を分けて派遣する。"
  },
  {
    "id": "20270926-iros-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-09-26",
    "year": 2027,
    "dateLabel": "9月26日–10月1日",
    "name": "IROS 2027",
    "budgetCandidate": false,
    "importance": "★★★★★",
    "businessFit": "★★★★☆",
    "category": "Robotics / Physical AI本体",
    "type": "学会・専門会議",
    "location": "Fortezza da Basso, Florence, Italy",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "知能ロボット・ロボットシステムの分野トップ会議。部門予算化はせず、論文・発表と個別参加判断の参考情報として管理する。"
  },
  {
    "id": "20271002-iccv-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-10-02",
    "year": 2027,
    "dateLabel": "10月2–8日",
    "name": "ICCV 2027",
    "budgetCandidate": false,
    "importance": "★★★★★",
    "businessFit": "★★★☆☆",
    "category": "Vision / 3D認識",
    "type": "学会・専門会議",
    "location": "Hong Kong",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "画像認識、3D認識、視覚基盤モデル。CVPR・ECCVと並ぶComputer Visionのトップティア会議として、論文・発表を追跡する。",
    "sourceUrl": "https://www.thecvf.com/?p=137",
    "verifiedAt": "2026-09-16"
  },
  {
    "id": "20271004-emo-milano-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-10-04",
    "year": 2027,
    "dateLabel": "10月4–9日",
    "name": "EMO Milano 2027",
    "budgetCandidate": true,
    "importance": "★★☆☆☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Fieramilano, Milan, Italy",
    "status": "2027計画",
    "assignment": "～2名",
    "purpose": "工作機械・金属加工"
  },
  {
    "id": "20271026-formnext-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-10-26",
    "year": 2027,
    "dateLabel": "10月26–29日",
    "name": "Formnext 2027",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Frankfurt Fair & Exhibition Centre, Frankfurt am Main, Germany",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "アディティブマニュファクチャリング、工業用3Dプリンティング、材料、次世代製造技術。部門の参加・予算計画には含めず、関連テーマの参考情報として管理する。"
  },
  {
    "id": "20271116-semicon-europa-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-11-16",
    "year": 2027,
    "dateLabel": "11月16–19日",
    "name": "SEMICON Europa 2027",
    "budgetCandidate": true,
    "importance": "★★☆☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Trade Fair Center Messe München, Munich, Germany",
    "status": "2027計画",
    "assignment": "TBD",
    "purpose": "欧州半導体装置・材料・プロセス。部門予算化計画。"
  },
  {
    "id": "20271123-sps-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-11-23",
    "year": 2027,
    "dateLabel": "11月23–25日",
    "name": "SPS 2027",
    "budgetCandidate": true,
    "importance": "★★★☆☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Exhibition Centre Nuremberg, Nuremberg, Germany",
    "status": "2027計画",
    "assignment": "～2名",
    "purpose": "Smart Production Solutions。FA、PLC、産業制御、産業通信、ドライブ、センサ、Industrial AIを確認する基幹候補。"
  },
  {
    "id": "20271130-siggraph-asia-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-11-30",
    "year": 2027,
    "dateLabel": "11月30日–12月3日",
    "name": "SIGGRAPH Asia 2027",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★★★☆",
    "category": "Simulation / Digital Twin / CG",
    "type": "学会・専門会議",
    "location": "Tokyo International Forum, Tokyo, Japan",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "Computer Graphics、Simulation、Digital Twin、3D表現、生成表現。2027年は東京開催。",
    "sourceUrl": "https://asia.siggraph.org/2026/about-the-event/siggraph-asia-2027/",
    "verifiedAt": "2026-09-16"
  },
  {
    "id": "20271214-cdc-2027",
    "dateStatus": "confirmed",
    "sortDate": "2027-12-14",
    "year": 2027,
    "dateLabel": "12月14–17日",
    "name": "CDC 2027",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★☆☆",
    "category": "Control / Motion / Systems",
    "type": "学会・専門会議",
    "location": "Lisbon, Portugal",
    "status": "参考情報",
    "assignment": "—",
    "purpose": "IEEE Conference on Decision and Control。制御理論・意思決定・最適制御。会場名は主催学会から未公表。",
    "sourceUrl": "https://ieeecss.org/conferences",
    "verifiedAt": "2026-09-23"
  },
  {
    "id": "20280403-modex-2028",
    "dateStatus": "confirmed",
    "sortDate": "2028-04-03",
    "year": 2028,
    "dateLabel": "4月3–5日",
    "name": "MODEX 2028",
    "budgetCandidate": true,
    "importance": "★★★☆☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Georgia World Congress Center, Atlanta, GA, United States",
    "status": "2028計画",
    "assignment": "TBD",
    "purpose": "ProMat 2027と相互補完で見る物流・マテハン・サプライチェーン展示会。",
    "sourceUrl": "https://www.modexshow.com/",
    "verifiedAt": "2026-09-16"
  },
  {
    "id": "20280404-interclean-amsterdam-2028",
    "dateStatus": "confirmed",
    "sortDate": "2028-04-04",
    "year": 2028,
    "dateLabel": "4月4–7日",
    "name": "Interclean Amsterdam 2028",
    "budgetCandidate": true,
    "importance": "★★☆☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "RAI Amsterdam, Amsterdam, Netherlands",
    "status": "2028計画",
    "assignment": "TBD",
    "purpose": "清掃・衛生・サービスロボット・施設管理の業界実装確認。Interclean Amsterdamの次回開催として管理。"
  },
  {
    "id": "20281018-k-du-sseldorf-2028",
    "dateStatus": "confirmed",
    "sortDate": "2028-10-18",
    "year": 2028,
    "dateLabel": "10月18–25日",
    "name": "K Düsseldorf 2028",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "type": "展示会・見本市",
    "location": "Messe Düsseldorf, Düsseldorf, Germany",
    "status": "2028計画",
    "assignment": "TBD",
    "purpose": "プラスチック・ゴム、材料、成形加工、リサイクル、材料循環の大型展示会"
  },
  {
    "id": "pending-euroblech-2028",
    "dateStatus": "pending",
    "order": 0,
    "name": "EuroBLECH 2028",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "handling": "2028候補：TBD",
    "assignment": "TBD",
    "location": "Hannover Exhibition Grounds, Hannover, Germany（想定）",
    "purpose": "板金加工、レーザ、成形、加工自動化。隔年開催のためEuroBLECHの次回開催として管理。"
  },
  {
    "id": "pending-semicon-japan-2027",
    "dateStatus": "pending",
    "order": 1,
    "name": "SEMICON Japan 2027",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★★★★",
    "category": "International Exhibition / Market & Implementation",
    "handling": "2027候補：TBD",
    "assignment": "TBD",
    "location": "TBD",
    "purpose": "国内半導体装置・材料・プロセス。日程・場所はTBD"
  },
  {
    "id": "pending-corl-2027",
    "dateStatus": "pending",
    "order": 2,
    "name": "CoRL 2027",
    "budgetCandidate": false,
    "importance": "★★★★★",
    "businessFit": "★★★☆☆",
    "category": "Robot Learning / AI基盤",
    "handling": "2027候補：日程TBD",
    "assignment": "TBD",
    "location": "TBD",
    "purpose": "Robot Learning、VLA、Sim2Real、基盤モデルの中核会議。公式日程・開催地の発表後に5章へ移す。"
  },
  {
    "id": "pending-world-robot-conference-and-expo-2027",
    "dateStatus": "pending",
    "order": 3,
    "name": "World Robot Conference and Expo 2027",
    "budgetCandidate": true,
    "importance": "★★★★☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "handling": "2027候補：8月18日開幕／終了日TBD",
    "assignment": "TBD",
    "location": "Beijing, China（開催地未確認）",
    "purpose": "中国ロボット産業、ヒューマノイド、政策・標準化・社会実装。公式発表で2027年8月18日の開幕を確認。終了日と会場の発表後に5章へ移す。",
    "sourceUrl": "https://www.worldrobotconference.com/news/3616.html",
    "verifiedAt": "2026-09-16"
  },
  {
    "id": "pending-humanoid-robotics-summit-europe-2027",
    "dateStatus": "pending",
    "order": 4,
    "name": "Humanoid Robotics Summit Europe 2027",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★★★☆",
    "category": "Robotics / Physical AI本体",
    "handling": "2027候補：日程TBD",
    "assignment": "TBD",
    "location": "Stuttgart, Germany（想定）",
    "purpose": "欧州のヒューマノイド、Physical AI、産業実装・企業動向。2026年参加実績を踏まえ、公式日程発表後に5章へ移す。"
  },
  {
    "id": "pending-roscon-global-2027",
    "dateStatus": "pending",
    "order": 5,
    "name": "ROSCon Global 2027",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★☆",
    "category": "Embedded / Edge / Real-time Systems",
    "handling": "2027候補：日程TBD",
    "assignment": "TBD",
    "location": "TBD",
    "purpose": "ROS 2、ロボット実装基盤、OSS、開発ツール、シミュレーション連携。公式日程・開催地の発表待ち。"
  },
  {
    "id": "pending-icml-2027",
    "dateStatus": "pending",
    "order": 6,
    "name": "ICML 2027",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★☆☆☆",
    "category": "Robot Learning / AI基盤",
    "handling": "2027論文・発表追跡：TBD",
    "assignment": "TBD",
    "location": "South America（都市TBD）",
    "purpose": "機械学習本流。現地参加よりEmbodied AI、World Model、Robotics関連の論文・Workshop追跡を基本とし、日程・都市の公式発表後に再評価する。",
    "sourceUrl": "https://icml.cc/Conferences/FutureMeetings",
    "verifiedAt": "2026-09-16"
  },
  {
    "id": "pending-neurips-2027",
    "dateStatus": "pending",
    "order": 7,
    "name": "NeurIPS 2027",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★☆☆☆",
    "category": "Robot Learning / AI基盤",
    "handling": "2027論文・発表追跡：TBD",
    "assignment": "TBD",
    "location": "Europe",
    "purpose": "AI基盤のトップ会議。Embodied AI、World Model、Robotics関連Workshopと論文を追跡する。公式発表は欧州開催まで。"
  },
  {
    "id": "pending-asme-idetc-cie-2027",
    "dateStatus": "pending",
    "order": 8,
    "name": "ASME IDETC/CIE 2027",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★☆☆☆",
    "category": "Mechanical Design / Structural & Multidisciplinary Optimization",
    "handling": "2027候補：日程TBD",
    "assignment": "TBD",
    "location": "TBD",
    "purpose": "設計工学、Design Automation、CIE、メカ設計・最適化。ASME公式の案内は2027年版へ切り替わったが、日程・開催地は未発表。",
    "sourceUrl": "https://event.asme.org/IDETC-CIE",
    "verifiedAt": "2026-09-23"
  },
  {
    "id": "pending-irex-2027",
    "dateStatus": "pending",
    "order": 9,
    "name": "iREX 2027（国際ロボット展）",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★★☆",
    "category": "International Exhibition / Market & Implementation",
    "handling": "2027候補：12月上旬／日次TBD",
    "assignment": "TBD",
    "location": "Tokyo Big Sight, Tokyo, Japan",
    "purpose": "日本ロボット工業会主催の国内最大のロボット展。隔年・奇数年開催。日次の発表後に5章へ移す。渡航を伴わない。",
    "sourceUrl": "https://irex.nikkan.co.jp/",
    "verifiedAt": "2026-09-23"
  },
  {
    "id": "pending-rlc-2027",
    "dateStatus": "pending",
    "order": 10,
    "name": "RLC 2027",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★☆☆☆",
    "category": "Robot Learning / AI基盤",
    "handling": "2027候補：8月（日次TBD）",
    "assignment": "TBD",
    "location": "Brown University, United States ／ Odense, Denmark（想定）",
    "purpose": "強化学習専門の会議。2027年はEWRLとの共同開催で2会場に分かれる予定。日程・開催地の公式発表後に5章へ移す。",
    "sourceUrl": "https://rl-conference.cc/",
    "verifiedAt": "2026-09-23"
  },
  {
    "id": "pending-machina-summit-2027",
    "dateStatus": "pending",
    "order": 11,
    "name": "MACHINA Summit 2027",
    "budgetCandidate": false,
    "importance": "★★★★☆",
    "businessFit": "★★★☆☆",
    "category": "Robotics / Physical AI本体",
    "handling": "2027候補：7月（日次TBD）",
    "assignment": "TBD",
    "location": "Palais des Congrès, Paris, France",
    "purpose": "RAISE Summit系のPhysical AI・Humanoid・産業ロボットの会議。RAISE・MACHINAはHyve傘下になった。公式は「Palais des Congrès • Paris • July 2027」まで（9/16時点の検討リストにあったStation Fから会場が変わった）。日次の発表後に5章へ移す。RSS 2027（7/6–11、Athens）と時期が近い。",
    "sourceUrl": "https://www.machinasummit.com/",
    "verifiedAt": "2026-09-23"
  },
  {
    "id": "pending-the-physical-ai-expo-london-2027",
    "dateStatus": "pending",
    "order": 12,
    "name": "THE Physical AI Expo London 2027（11VC）",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★☆☆",
    "category": "Robotics / Physical AI本体",
    "handling": "2027候補：Q3（日程TBD）",
    "assignment": "TBD",
    "location": "ExCeL London, London, United Kingdom",
    "purpose": "11VC主催の初回開催。TechEx Events主催のPhysical AI Expo Globalとは別イベント。投資家・Enterprise Buyer・実機デモを前面に出す。6,000名・40超のライブデモは主催者の計画値で、実績ではない。",
    "sourceUrl": "https://www.thephysicalaiexpo.com/",
    "verifiedAt": "2026-09-23"
  },
  {
    "id": "pending-geia-europe-2027",
    "dateStatus": "pending",
    "order": 13,
    "name": "GEIA Europe 2027",
    "budgetCandidate": false,
    "importance": "★★★☆☆",
    "businessFit": "★★★☆☆",
    "category": "Robotics / Physical AI本体",
    "handling": "2027候補：日程TBD",
    "assignment": "TBD",
    "location": "Munich, Germany（想定）",
    "purpose": "GEIA Asiaと同じシリーズの欧州版（登壇40超・出展20超・300名超の見込み）。9/16時点の検討リストでは11月4–6日・Munichとしていたが、9/23の公式ページでは日程・都市を確認できなかった。Asiaとどちらか一方を選ぶ。HRS Europe・Advanced Humanoid Forumとテーマの重なりが大きい。",
    "sourceUrl": "https://www.geiaeurope.com/index.html",
    "verifiedAt": "2026-09-23"
  },
  {
    "id": "pending-physical-ai-summit-munich-2027",
    "dateStatus": "pending",
    "order": 14,
    "name": "Physical AI Summit Munich 2027",
    "budgetCandidate": false,
    "importance": "★★☆☆☆",
    "businessFit": "★★☆☆☆",
    "category": "Robotics / Physical AI本体",
    "handling": "2027候補：日程TBD",
    "assignment": "TBD",
    "location": "Munich, Germany",
    "purpose": "Dockland Media Group主催。2026年のSan Jose（9/17）に続く欧州版で、ワークショップ・コミュニティ形成型の小規模サミット。公式は「Save the date」のみで、日程・会場は未発表。",
    "sourceUrl": "https://www.physicalaiseries.com/events",
    "verifiedAt": "2026-09-23"
  },
  {
    "id": "pending-item",
    "dateStatus": "pending",
    "order": 15,
    "name": "年間予算予備枠（部門）",
    "budgetCandidate": true,
    "importance": "—",
    "businessFit": "—",
    "category": "部門予算枠",
    "handling": "2027年度年間枠",
    "assignment": "予備枠10名分",
    "location": "—",
    "purpose": "特定イベントに紐づけない追加派遣・追加調査用の年間予算予備枠。WRC固有の人数ではない。"
  }
];
